COPY CATADORES
	FROM 'C:\Users\Public\CATADORES_3_Tabular_All\CATADORES.tab' CSV HEADER DELIMITER E'\t';

COPY CATADORES_CONTATO_GRP_WHATS
	FROM 'C:\Users\Public\CATADORES_3_Tabular_All\R_CONTATO_GRP_WHATS.tab' CSV HEADER DELIMITER E'\t';

