COPY ABASTECIMENTO_AGUA 
	FROM 'C:\Users\Public\FUNASA_ABASTECIMENTO_AGUA_2_Tabular_All\FUNASA_ABASTECIMENTO_AGUA.tab' CSV HEADER DELIMITER E'\t';
  
COPY ABASTECIMENTO_AGUA_R_SITUACAO_PT_SUPER 
	FROM 'C:\Users\Public\FUNASA_ABASTECIMENTO_AGUA_2_Tabular_All\R_SITUACAO_PT_SUPER.tab' CSV HEADER DELIMITER E'\t';

COPY ABASTECIMENTO_AGUA_R_SITUACAO_PONT_SUB 
	FROM 'C:\Users\Public\FUNASA_ABASTECIMENTO_AGUA_2_Tabular_All\R_SITUACAO_PONT_SUB.tab' CSV HEADER DELIMITER E'\t';

COPY ABASTECIMENTO_AGUA_R_REGISTRO_DISTRIBUICAO 
	FROM 'C:\Users\Public\FUNASA_ABASTECIMENTO_AGUA_2_Tabular_All\R_REGISTRO_DISTRIBUICAO.tab' CSV HEADER DELIMITER E'\t';

COPY ABASTECIMENTO_AGUA_R_REGISTRO_AQ_TRAT 
	FROM 'C:\Users\Public\FUNASA_ABASTECIMENTO_AGUA_2_Tabular_All\R_REGISTRO_AQ_TRAT.tab' CSV HEADER DELIMITER E'\t';

COPY ABASTECIMENTO_AGUA_R_REGISTRO_AQ_BRUTA 
	FROM 'C:\Users\Public\FUNASA_ABASTECIMENTO_AGUA_2_Tabular_All\R_REGISTRO_AQ_BRUTA.tab' CSV HEADER DELIMITER E'\t';

COPY ABASTECIMENTO_AGUA_R_NUMERO_LIGACOES 
	FROM 'C:\Users\Public\FUNASA_ABASTECIMENTO_AGUA_2_Tabular_All\R_NUMERO_LIGACOES.tab' CSV HEADER DELIMITER E'\t';
	
COPY ABASTECIMENTO_AGUA_R_BAIRRO_SIST_DIST 
	FROM 'C:\Users\Public\FUNASA_ABASTECIMENTO_AGUA_2_Tabular_All\R_BAIRRO_SIST_DIST.tab' CSV HEADER DELIMITER E'\t';
