INSERT INTO ABASTECIMENTO_AGUA_EXIST_REG_AQ_TRAT (ID, DESCRICAO) VALUES
(1, 'Descarga'),
(2, 'Ventosa');

INSERT INTO ABASTECIMENTO_AGUA_EXISTE_REG_DIST (ID, DESCRICAO) VALUES
(1, 'SIM'),
(2, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_R_SITUACAO_PONT_SUB__id (ID, DESCRICAO) VALUES
(1, 'Licença Operacional'),
(2, 'Outorga');

INSERT INTO ABASTECIMENTO_AGUA_R_SITUACAO_PT_SUPER__id (ID, DESCRICAO) VALUES
(1, 'Licença Operacional'),
(2, 'Outorga');

INSERT INTO ABASTECIMENTO_AGUA_R_NUMERO_LIGACOES__id (ID, DESCRICAO) VALUES
(1, 'Ligações'),
(2, 'Economias');

INSERT INTO ABASTECIMENTO_AGUA_TIP_MAT_AQ_TRAT (ID, DESCRICAO) VALUES
(0, 'PVC'),
(1, 'Ferro Fundido'),
(2, 'Aço Corrugado'),
(3, 'Outros');

INSERT INTO ABASTECIMENTO_AGUA_REG_MANOB_AQ_TRAT (ID, DESCRICAO) VALUES
(1, 'SIM'),
(2, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_EXISTE_DIS_AUX_AQ_TRAT (ID, DESCRICAO) VALUES
(1, 'SIM'),
(2, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_FONTE_PT_SUPER (ID, DESCRICAO) VALUES
(0, 'Rio'),
(1, 'Mina'),
(2, 'Lago'),
(3, 'Reservatório'),
(4, 'Outros');

INSERT INTO ABASTECIMENTO_AGUA_EXISTE_MAC_MED_PT (ID, DESCRICAO) VALUES
(1, 'SIM'),
(0, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_EXIST_CAD_PLANTAS_PT_SUPER (ID, DESCRICAO) VALUES
(1, 'SIM'),
(0, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_TIPO_CAP_PT_SUPER (ID, DESCRICAO) VALUES
(0, 'Direta'),
(1, 'Flutuador'),
(2, 'Tubulão'),
(3, 'Outro');

INSERT INTO ABASTECIMENTO_AGUA_TIPO_BOMBA_PT_SUPER (ID, DESCRICAO) VALUES
(0, 'Eixo vertical'),
(1, 'Eixo horizontal');

INSERT INTO ABASTECIMENTO_AGUA_LIG_BOMBA_PT_SUPER (ID, DESCRICAO) VALUES
(0, 'Mono'),
(1, 'Bifásica'),
(2, 'Trifásica');

INSERT INTO ABASTECIMENTO_AGUA_BOMBEA_BOMBA_RES_PT_SUPER (ID, DESCRICAO) VALUES
(0, 'FTA'),
(1, 'Reservatório');

INSERT INTO ABASTECIMENTO_AGUA_MANUT_BOMBA_PT_SUPER (ID, DESCRICAO) VALUES
(0, 'SIM'),
(1, 'Não, a manutenção só é feita quando há problemas na bomba');

INSERT INTO ABASTECIMENTO_AGUA_MANUT_PREV_BOMB (ID, DESCRICAO) VALUES
(0, 'Diária'),
(1, 'Semanal'),
(2, 'Mensal'),
(3, 'Anual'),
(4, 'Outro');

INSERT INTO ABASTECIMENTO_AGUA_MANUT_PREV_BOMB2 (ID, DESCRICAO) VALUES
(0, 'Diária'),
(1, 'Semanal'),
(2, 'Mensal'),
(3, 'Anual'),
(4, 'Outro');

INSERT INTO ABASTECIMENTO_AGUA_CONFLIT_RECURSO2 (ID, DESCRICAO) VALUES
(0, 'SIM'),
(1, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_CONFLIT_RECURSO (ID, DESCRICAO) VALUES
(0, 'SIM'),
(1, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_EXISTE_BOMBA_RES_PT_SUPER (ID, DESCRICAO) VALUES
(1, 'NÃO'),
(0, 'SIM');

INSERT INTO ABASTECIMENTO_AGUA_CARAC_BOMBA_RES_PRIN_PT_SUPER (ID, DESCRICAO) VALUES
(1, 'NÃO'),
(0, 'SIM');


INSERT INTO ABASTECIMENTO_AGUA_LIG_BOMBA_RES_PT_SUPER (ID, DESCRICAO) VALUES
(0, 'Mono'),
(1, 'Bifásica'),
(2, 'Trifásica');

INSERT INTO ABASTECIMENTO_AGUA_DIST_CAP_SIST_PT_SUPER (ID, DESCRICAO) VALUES
(0, 'SIM'),
(1, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_TIPO_RESERVATORIO_RESERVACAO (ID, DESCRICAO) VALUES
(0, 'Elevado'),
(1, 'Apoiado'),
(2, 'Enterrado'),
(3, 'Outro');

INSERT INTO ABASTECIMENTO_AGUA_MAT_COMP_RESERVACAO (ID, DESCRICAO) VALUES
(0, 'Concreto Armado'),
(1, 'Aço'),
(2, 'Poliéster armado com fibras de vidro'),
(3, 'Outro');

INSERT INTO ABASTECIMENTO_AGUA_FORMA_RESERVATORIO_RESERVACAO (ID, DESCRICAO) VALUES
(0, 'Circular'),
(1, 'Retangular'),
(2, 'Outro');

INSERT INTO ABASTECIMENTO_AGUA_SIT_OP_RESERVACAO (ID, DESCRICAO) VALUES
(0, 'Ativo'),
(1, 'Inativo');


INSERT INTO ABASTECIMENTO_AGUA_TIPO_ESTA_TRAT (ID, DESCRICAO) VALUES
(0, 'Estação Convencional'),
(1, 'ETA Compacta Metálica Fechada'),
(2, 'ETA Compacta Metálica Aberta'),
(3, 'Outra');

INSERT INTO ABASTECIMENTO_AGUA_TIPO_TRAT_TRAT (ID, DESCRICAO) VALUES
(0, 'Simplificado'),
(1, 'Convencional'),
(2, 'Aberta');

INSERT INTO ABASTECIMENTO_AGUA_MIST_RAP_TRAT (ID, DESCRICAO) VALUES
(0, 'Mecânica'),
(1, 'Hidráulica');

INSERT INTO ABASTECIMENTO_AGUA_COAG_TRAT (ID, DESCRICAO) VALUES
(0, 'SIM'),
(1, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_TIPO_FLOCU_TRAT (ID, DESCRICAO) VALUES
(0, 'Mecânico'),
(1, 'Hidráulico');

INSERT INTO ABASTECIMENTO_AGUA_FLUXO_TRAT (ID, DESCRICAO) VALUES
(0, 'Horizontal'),
(1, 'Vertical'),
(2, 'Misto');

INSERT INTO ABASTECIMENTO_AGUA_TIPO_DECAN_TRAT (ID, DESCRICAO) VALUES
(0, 'Placa'),
(1, 'Convencional');

INSERT INTO ABASTECIMENTO_AGUA_FILTRO_DIST (ID, DESCRICAO) VALUES
(0, 'Ascendente'),
(1, 'Descendente');

INSERT INTO ABASTECIMENTO_AGUA_CAMADA_TRAT (ID, DESCRICAO) VALUES
(0, 'UMA'),
(1, 'MÚLTIPLAS');

INSERT INTO ABASTECIMENTO_AGUA_MAT_FILT_TRAT (ID, DESCRICAO) VALUES
(0, 'Areia'),
(1, 'Antracito'),
(2, 'Outro');

INSERT INTO ABASTECIMENTO_AGUA_SIST_PROT_TRAT (ID, DESCRICAO) VALUES
(0, 'SIM'),
(1, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_FLUORE_TRAT (ID, DESCRICAO) VALUES
(0, 'SIM'),
(1, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_TRAT (ID, DESCRICAO) VALUES
(0, 'Sulfato de alumínio'),
(1, 'Sulfato de Ferro'),
(0, 'Outro');

INSERT INTO ABASTECIMENTO_AGUA_EXISTE_PLAN_TRAT (ID, DESCRICAO) VALUES
(0, 'SIM'),
(1, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_EXIST_ESTAC_TRAT (ID, DESCRICAO) VALUES
(1, 'SIM'),
(0, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_TIP_MAT_AQ_BRUTA (ID, DESCRICAO) VALUES
(0, 'PVC'),
(1, 'Ferro Fundido'),
(2, 'Aço Corrugado'),
(3, 'Outros');

INSERT INTO ABASTECIMENTO_AGUA_REG_MANOB_AQ_BRUTA (ID, DESCRICAO) VALUES
(1, 'SIM'),
(0, 'NÃO');


INSERT INTO ABASTECIMENTO_AGUA_EXISTE_DIS_AUX_AQ_BRUTA (ID, DESCRICAO) VALUES
(1, 'SIM'),
(0, 'NÃO');


INSERT INTO ABASTECIMENTO_AGUA_VAL_RET_AQ_BRUTA (ID, DESCRICAO) VALUES
(1, 'SIM'),
(0, 'NÃO');


INSERT INTO ABASTECIMENTO_AGUA_PROB_EXIS_AQ_BRUTA (ID, DESCRICAO) VALUES
(0, 'SIM'),
(1, 'NÃO');


INSERT INTO ABASTECIMENTO_AGUA_POLIT_TARIF_GERAIS (ID, DESCRICAO) VALUES
(0, 'Taxa'),
(1, 'Tarifa'),
(2, 'Abastecimento gratuito'),
(3, 'Outro');

INSERT INTO ABASTECIMENTO_AGUA_EXISTE_TAR_SOC_GERAIS (ID, DESCRICAO) VALUES
(0, 'SIM'),
(1, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_PRINC_RECLA_GERAIS (ID, DESCRICAO) VALUES
(0, 'Reclamação de interrupção no abastecimento de água'),
(1, 'Reclamação sobre a qualidade da água'),
(2, 'Reclamação sobre valores ou erro de leitura'),
(3, 'Reclamação sobre vazamentos'),
(4, 'Pressão da Rede'),
(5, 'Outra');

INSERT INTO ABASTECIMENTO_AGUA_EXIST_GERADOR_SIST (ID, DESCRICAO) VALUES
(0, 'SIM'),
(1, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_EXIST_GERADOR_SIST3 (ID, DESCRICAO) VALUES
(0, 'Manual'),
(1, 'Automático');

INSERT INTO ABASTECIMENTO_AGUA_SIST_AUTO_GERAIS (ID, DESCRICAO) VALUES
(0, 'SIM'),
(1, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_EQUIPE_TEC_QUALI_GERAIS (ID, DESCRICAO) VALUES
(0, 'SIM'),
(1, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_REL_OP_DESP_GERAIS (ID, DESCRICAO) VALUES
(0, 'SIM'),
(1, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_LICENCA_ABASTECIMENTO (ID, DESCRICAO) VALUES
(0, 'SIM'),
(1, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_PRESTADOR_SERVICOS (ID, DESCRICAO) VALUES
(0, 'Autarquia'),
(1, 'Empresa Privada'),
(2, 'Sociedade'),
(3, 'Economia Mista'),
(4, 'Outros');

INSERT INTO ABASTECIMENTO_AGUA_PRESTADOR_SERVICOS3 (ID, DESCRICAO) VALUES
(0, 'SIM'),
(1, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_PRESTADOR_SERVICOS7 (ID, DESCRICAO) VALUES
(0, 'SIM'),
(1, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_PLAN_DIRETOR_EXIST (ID, DESCRICAO) VALUES
(0, 'SIM'),
(1, 'NÃO');

INSERT INTO ABASTECIMENTO_AGUA_MUNIC_MANANCIAL (ID, DESCRICAO) VALUES
(1, 'Guajará-Mirim'),
(2, 'Costa Marques'),
(3, 'Castanheiras'),
(4, 'Ministro Andreazza'),
(5, 'Ouro Preto do Oeste'),
(6, 'Teixeirópolis'),
(7, 'Urupá'),
(8, 'Vale do Paraíso'),
(9, 'Alta Floresta'),
(10, 'Alto Alegre dos Parecis'),
(11, 'Novo Horizonte do Oeste'),
(12, 'Parecis'),
(13, 'Primavera de Rondônia'),
(14, 'São Felipe'),
(15, 'Cabixi'),
(16, 'Colorado do Oeste'),
(17, 'Chupinguaia'),
(18, 'Pimenta Bueno'),
(19, 'Pimenteiras do Oeste');
