COPY DADOS_URBANOS 
	FROM 'C:\Users\Public\DADOS_URBANOS.tab' CSV HEADER DELIMITER E'\t';

COPY DADOS_URBANOS_R_ESCOLARIDADE_FAM 
	FROM 'C:\Users\Public\R_ESCOLARIDADE_FAM.tab' CSV HEADER DELIMITER E'\t';

COPY DADOS_URBANOS_R_CONTATO_GRP_WHATS
	FROM 'C:\Users\Public\R_CONTATO_GRP_WHATS.tab' CSV HEADER DELIMITER E'\t';

COPY DADOS_URBANOS_R_EVENTO_FESTIVO 
	FROM 'C:\Users\Public\R_EVENTO_FESTIVO.tab' CSV HEADER DELIMITER E'\t';


