COPY ESGOTAMENTO_SANITARIO_DESP_MEDI_MEN_ANO
    FROM 'C:\Users\Public\ESGOTAMENTO\DESP_MEDI_MEN_ANO.tab' CSV HEADER DELIMITER E'\t'

COPY ESGOTAMENTO_SANITARIO_CONTR_ASP_LEGS
    FROM 'C:\Users\Public\ESGOTAMENTO\CONTR_ASP_LEGS.tab' CSV HEADER DELIMITER E'\t'

COPY ESGOTAMENTO_SANITARIO_DADOS_GERAIS_ESGOT
    FROM 'C:\Users\Public\ESGOTAMENTO\DADOS_GERAIS_ESGOT.tab' CSV HEADER DELIMITER E'\t'

COPY ESGOTAMENTO_SANITARIO_FTS_CONTR
    FROM 'C:\Users\Public\ESGOTAMENTO\FTS_CONTR.tab' CSV HEADER DELIMITER E'\t'

COPY ESGOTAMENTO_SANITARIO_GR_ESCOL_FUN
    FROM 'C:\Users\Public\ESGOTAMENTO\GR_ESCOL_FUN.tab' CSV HEADER DELIMITER E'\t'

COPY ESGOTAMENTO_SANITARIO_INF_QULDD_ESGOT
    FROM 'C:\Users\Public\ESGOTAMENTO\INF_QULDD_ESGOT.tab' CSV HEADER DELIMITER E'\t'

COPY ESGOTAMENTO_SANITARIO_INVEST_VALOR
    FROM 'C:\Users\Public\ESGOTAMENTO\INVEST_VALOR.tab' CSV HEADER DELIMITER E'\t'

COPY ESGOTAMENTO_SANITARIO_LOCALIDADE_CIEL
    FROM 'C:\Users\Public\ESGOTAMENTO\LOCALIDADE_CIEL.tab' CSV HEADER DELIMITER E'\t'

COPY ESGOTAMENTO_SANITARIO_DESPSAS_ESGOT
    FROM 'C:\Users\Public\ESGOTAMENTO\DESPSAS_ESGOT.tab' CSV HEADER DELIMITER E'\t'

COPY ESGOTAMENTO_SANITARIO_NUM_MENSAL
    FROM 'C:\Users\Public\ESGOTAMENTO\NUM_MENSAL.tab' CSV HEADER DELIMITER E'\t'

COPY ESGOTAMENTO_SANITARIO_RECEITAS_ESGOT
    FROM 'C:\Users\Public\ESGOTAMENTO\RECEITAS_ESGOT.tab' CSV HEADER DELIMITER E'\t'

COPY ESGOTAMENTO_SANITARIO_DADOSBAC_IDEN
    FROM 'C:\Users\Public\ESGOTAMENTO\DADOSBAC_IDEN.tab' CSV HEADER DELIMITER E'\t'

COPY ESGOTAMENTO_SANITARIO_DADOSDASUBBACIA
    FROM 'C:\Users\Public\ESGOTAMENTO\DADOSDASUBBACIA.tab' CSV HEADER DELIMITER E'\t'

COPY ESGOTAMENTO_SANITARIO_DADOSESGOTAMENTOINDIVI
    FROM 'C:\Users\Public\ESGOTAMENTO\DADOSESGOTAMENTOINDIVI.tab' CSV HEADER DELIMITER E'\t'

COPY ESGOTAMENTO_SANITARIO_FREQUENCIADEANAL
    FROM 'C:\Users\Public\ESGOTAMENTO\FREQUENCIADEANAL.tab' CSV HEADER DELIMITER E'\t'

COPY ESGOTAMENTO_SANITARIO
    FROM 'C:\Users\Public\ESGOTAMENTO\ESGOTAMENTO_SANITARIO.tab' CSV HEADER DELIMITER E'\t'

COPY ESGOTAMENTO_SANITARIO_DADOSSISTEELEVA
    FROM 'C:\Users\Public\ESGOTAMENTO\DADOSSISTEELEVA.tab' CSV HEADER DELIMITER E'\t'

COPY ESGOTAMENTO_SANITARIO_DADOSLANCEFLU
    FROM 'C:\Users\Public\ESGOTAMENTO\DADOSLANCEFLU.tab' CSV HEADER DELIMITER E'\t'

COPY ESGOTAMENTO_SANITARIO_DADOSETE
    FROM 'C:\Users\Public\ESGOTAMENTO\DADOSETE.tab' CSV HEADER DELIMITER E'\t'
