COPY RESIDUOS_SOLIDOS_FUNASA_RESIDUOS_SOLIDOS
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\FUNASA_RESIDUOS_SOLIDOS.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_FREQ_COLETA_RSD
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\FREQ_COLETA_RSD.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_IMAGENS_CATADORES_R
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\IMAGENS_CATADORES_R.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_INFORM_ESTUDOS_TEC
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\INFORM_ESTUDOS_TEC.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_INFORM_PROJ_TEC
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\INFORM_PROJ_TEC.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_INFOUNIDGERADORA
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\INFOUNIDGERADORA.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_MELHOR_FORMA_SER_FEITO
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\MELHOR_FORMA_SER_FEITO.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_MOTOR_COLET_BOLSOES
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\MOTOR_COLET_BOLSOES.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_MOTOR_COLET_RSD
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\MOTOR_COLET_RSD.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_NAT_JURID_CONTRATOS
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\NAT_JURID_CONTRATOS.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_QTD_TT_RES_17_18
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\QTD_TT_RES_17_18.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_CAP_TREI_FUN_LIMP_URB
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_CAP_TREI_FUN_LIMP_URB.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_COM_LOC_RSC
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_COM_LOC_RSC.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_CUSTO_SERV_LP
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_CUSTO_SERV_LP.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_EQUIP_FERRAM
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_EQUIP_FERRAM.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_ESC_FUN_LIM_PUB
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_ESC_FUN_LIM_PUB.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_EXISTENCIA
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_EXISTENCIA.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_GASTOS_PESSOAL
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_GASTOS_PESSOAL.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_IMG_PROCESSAMENTO
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_IMG_PROCESSAMENTO.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_IMG_RCC
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_IMG_RCC.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_IMG_RSC
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_IMG_RSC.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_IMG_RSI
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_IMG_RSI.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_IMG_RSS
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_IMG_RSS.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_IND_LOC_RSI
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_IND_LOC_RSI.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_LOCALIDADE
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_LOCALIDADE.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_OUTROS_CUSTOS
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_OUTROS_CUSTOS.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_PRIN_RES_GER_RSI
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_PRIN_RES_GER_RSI.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_PRINC_RES_GER_RSC
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_PRINC_RES_GER_RSC.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_QUANT_COL_MES_RCC
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_QUANT_COL_MES_RCC.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_QUANT_ECON_ATEND
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_QUANT_ECON_ATEND.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_RESP_INFORM
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_RESP_INFORM.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_SIST_COB_17_18
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_SIST_COB_17_18.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_UNI_GERADORA
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_UNI_GERADORA.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_R_VAL_PREV_REAL
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\R_VAL_PREV_REAL.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_RESIDUOS_REC_ENV
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\RESIDUOS_REC_ENV.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROST_CUST_MED_ANUAL
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_CUST_MED_ANUAL.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROST_FT_LIMP_URB
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_FT_LIMP_URB.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROST_GR_ESCOL_FUN
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_GR_ESCOL_FUN.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROST_INFO_LOC
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_INFO_LOC.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROST_OBS_CLT_SLTV
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_OBS_CLT_SLTV.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROST_OBSERV_FT
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_OBSERV_FT.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROST_QTDE_FOTO_RST
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_QTDE_FOTO_RST.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROST_RES_GER_LOC
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_RES_GER_LOC.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROST_RESP_AELSLU
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_RESP_AELSLU.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROST_RESP_AL
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_RESP_AL.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROST_RESP_CARG_FUNC
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_RESP_CARG_FUNC.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROST_RESP_INFO_CARG
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_RESP_INFO_CARG.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROST_RESP_LIMP_URB
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_RESP_LIMP_URB.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROST_RESP_RCC
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_RESP_RCC.tab' CSV HEADER DELIMITER E'\t';


COPY RESIDUOS_SOLIDOS_ROST_RESP_RSC
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_RESP_RSC.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROST_RESP_RSS
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_RESP_RSS.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROST_RESP_RST
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_RESP_RST.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROST_SALVADOR
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_SALVADOR.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROST_SERVI_LIMP_PUB
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROST_SERVI_LIMP_PUB.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROSTER_INF_COLET_SELET
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROSTER_INF_COLET_SELET.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_ROSTER_TRIA_MAT
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\ROSTER_TRIA_MAT.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_TRATAM_DISP_FINAL
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\TRATAM_DISP_FINAL.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_VEIC_EQUIP_EMPRESA
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\VEIC_EQUIP_EMPRESA.tab' CSV HEADER DELIMITER E'\t';

COPY RESIDUOS_SOLIDOS_VEIC_EQUIP_PREF
	FROM 'C:\Users\Public\FUNASA_RESIDUOS_SOLIDOS_2_Tabular_All\VEIC_EQUIP_PREF.tab' CSV HEADER DELIMITER E'\t';
