CREATE TABLE RESIDUOS_SOLIDOS (

    interview__key VARCHAR(12),
    interview__id VARCHAR(32),

    NUCLEO INT,
    MUNICIPIO INT,

    LEGISLACAO_EXISTENTE__1 SMALLINT NULL,
    LEGISLACAO_EXISTENTE__2 SMALLINT NULL,
    LEGISLACAO_EXISTENTE__3 SMALLINT NULL,
    LEGISLACAO_EXISTENTE__4 SMALLINT NULL,
    LEGISLACAO_EXISTENTE__5 SMALLINT NULL,
    LEGISLACAO_EXISTENTE__6 SMALLINT NULL,

    ESPEC_LEGISLACAO_EX VARCHAR (140),

    PENA_MUNICIPIO INT,

    ESPEC_PENA_MUNIC VARCHAR (140),
    MEDIDAS_TOMADAS VARCHAR (140),

    REGULAMENTOS_EXIST INT,

     LEGIS_REGULAMENTOS__1 SMALLINT NULL,
    LEGIS_REGULAMENTOS__2 SMALLINT NULL,
    LEGIS_REGULAMENTOS__3 SMALLINT NULL,
    LEGIS_REGULAMENTOS__4 SMALLINT NULL,
    LEGIS_REGULAMENTOS__5 SMALLINT NULL,
    LEGIS_REGULAMENTOS__6 SMALLINT NULL,
    LEGIS_REGULAMENTOS__7 SMALLINT NULL,
    LEGIS_REGULAMENTOS__8 SMALLINT NULL,

    EPEC_LEG_REGULAM VARCHAR (140),
    ANEXOS_LEIS VARCHAR (140),
    ESTUDOS_TECNICOS INT,

    TP_ESTUDOS_TEC__1 SMALLINT NULL,
    TP_ESTUDOS_TEC__2 SMALLINT NULL,
    TP_ESTUDOS_TEC__3 SMALLINT NULL,
    TP_ESTUDOS_TEC__4 SMALLINT NULL,
    TP_ESTUDOS_TEC__5 SMALLINT NULL,

    PROJET_TECNICOS INT,

    ESPEC_PROJETOS__1 SMALLINT NULL,
    ESPEC_PROJETOS__2 SMALLINT NULL,
    ESPEC_PROJETOS__3 SMALLINT NULL,
    ESPEC_PROJETOS__4 SMALLINT NULL,
    ESPEC_PROJETOS__5 SMALLINT NULL,
    ESPEC_PROJETOS__6 SMALLINT NULL,

    RESP_INF_AL__0 VARCHAR (140), --list
    RESP_INF_AL__1 VARCHAR (140),
    RESP_INF_AL__2 VARCHAR (140),
    RESP_INF_AL__3 VARCHAR (140),
    RESP_INF_AL__4 VARCHAR (140),
    RESP_INF_AL__5 VARCHAR (140),
    RESP_INF_AL__6 VARCHAR (140),
    RESP_INF_AL__7 VARCHAR (140),
    RESP_INF_AL__8 VARCHAR (140),
    RESP_INF_AL__9 VARCHAR (140),
    RESP_INF_AL__10 VARCHAR (140),
    RESP_INF_AL__11 VARCHAR (140),
    RESP_INF_AL__12 VARCHAR (140),
    RESP_INF_AL__13 VARCHAR (140),
    RESP_INF_AL__14 VARCHAR (140),

    OBS_AL VARCHAR (300),

    ASSE_TEC_SLU INT,
    PREST_ASSE_TEC_SLU INT,

    OUTRA_PREST_ASSE_TEC_SLU VARCHAR (140),
    MUN_PREST_ASSE_TEC_SLU VARCHAR (140),

    EXIST_SET_FUN_TRAB_SIST INT,

    NUMFUNCTRAB DECIMAL,

    CAPACT_FUNC_SIST_ESGOT INT,

    QTDD_HORA_CAPACT DECIMAL,

    ESC_RESP_GRS INT,

    RESP_INF_AAITSLU__0 VARCHAR (140), --list
    RESP_INF_AAITSLU__1 VARCHAR (140),
    RESP_INF_AAITSLU__2 VARCHAR (140),
    RESP_INF_AAITSLU__3 VARCHAR (140),
    RESP_INF_AAITSLU__4 VARCHAR (140),
    RESP_INF_AAITSLU__5 VARCHAR (140),
    RESP_INF_AAITSLU__6 VARCHAR (140),
    RESP_INF_AAITSLU__7 VARCHAR (140),
    RESP_INF_AAITSLU__8 VARCHAR (140),
    RESP_INF_AAITSLU__9 VARCHAR (140),
    RESP_INF_AAITSLU__10 VARCHAR (140),
    RESP_INF_AAITSLU__11 VARCHAR (140),
    RESP_INF_AAITSLU__12 VARCHAR (140),
    RESP_INF_AAITSLU__13 VARCHAR (140),
    RESP_INF_AAITSLU__14 VARCHAR (140),

    OBS_AAITSLU VARCHAR (300),

    SIST_COB_SERV_RES_SOL INT,

    OUTRO_SIST_COB_RS VARCHAR (140),
    MESMO_SIST_COB INT,

    FONTES_REC_SLU__0 SMALLINT NULL,
    FONTES_REC_SLU__1 SMALLINT NULL,
    FONTES_REC_SLU__2 SMALLINT NULL,
    FONTES_REC_SLU__3 SMALLINT NULL,
    FONTES_REC_SLU__4 SMALLINT NULL,
    FONTES_REC_SLU__5 SMALLINT NULL,
    FONTES_REC_SLU__6 SMALLINT NULL,

    OUTRA_FONTE_REC_SLU VARCHAR (140),

    RESP_INF__0 VARCHAR (140), --list
    RESP_INF__1 VARCHAR (140),
    RESP_INF__2 VARCHAR (140),
    RESP_INF__3 VARCHAR (140),
    RESP_INF__4 VARCHAR (140),
    RESP_INF__5 VARCHAR (140),
    RESP_INF__6 VARCHAR (140),
    RESP_INF__7 VARCHAR (140),
    RESP_INF__8 VARCHAR (140),
    RESP_INF__9 VARCHAR (140),
    RESP_INF__10 VARCHAR (140),
    RESP_INF__11 VARCHAR (140),
    RESP_INF__12 VARCHAR (140),
    RESP_INF__13 VARCHAR (140),
    RESP_INF__14 VARCHAR (140),

    OBS_ADD VARCHAR (300),

    LOC_RESI__0 VARCHAR (140), --list
    LOC_RESI__1 VARCHAR (140),
    LOC_RESI__2 VARCHAR (140),
    LOC_RESI__3 VARCHAR (140),
    LOC_RESI__4 VARCHAR (140),
    LOC_RESI__5 VARCHAR (140),
    LOC_RESI__6 VARCHAR (140),
    LOC_RESI__7 VARCHAR (140),
    LOC_RESI__8 VARCHAR (140),
    LOC_RESI__9 VARCHAR (140),

    sssys_irnd DOUBLE PRECISION,
    has__errors SMALLINT,
    interview__status SMALLINT

);

---- ROSTERS

CREATE TABLE RESIDUOS_SOLIDOS_MELHOR_FORMA_SER_FEITO (

    interview__key VARCHAR(12),
    interview__id VARCHAR(32),

    R_LOCALIDADE__id INT,
    MELHOR_FORMA_SER_FEITO__id INT,

    RESP_INFO_CLT_SLTV VARCHAR (140),

    CARG_OU_FUNCAO VARCHAR (140)


);

CREATE TABLE RESIDUOS_SOLIDOS_IMAGENS_CATADORES_R (

    interview__key VARCHAR(12),
    interview__id VARCHAR(32),

    R_LOCALIDADE__id INT,
    IMAGENS_CATADORES_R__id INT,

    IMAGENS_CATADORES_R2 VARCHAR (140)

);

CREATE TABLE RESIDUOS_SOLIDOS_NAT_JURID_CONTRATOS (

    interview__key VARCHAR(12),
    interview__id VARCHAR(32),

    NAT_JURID_CONTRATOS__id INT,

    NATUREZA_JURIDICA INT,
    TIPO_CONTRATO INT,

    CONTRATO  VARCHAR (140)


);

CREATE TABLE RESIDUOS_SOLIDOS_INFORM_ESTUDOS_TEC (

    interview__key VARCHAR(12),
    interview__id VARCHAR(32),

    INFORM_ESTUDOS_TEC__id INT,

    ANO_ESTUDO_TEC VARCHAR (140),

    SITUACAO_PLANO INT,
    REVISAO_PLANO INT,


);


CREATE TABLE RESIDUOS_SOLIDOS_INFORM_PROJ_TEC (

    interview__key VARCHAR(12),
    interview__id VARCHAR(32),

    INFORM_PROJ_TEC__id INT,

    ANO_PROJETO VARCHAR (140),
    SITUACAO_PROJ INT,
);


CREATE TABLE RESIDUOS_SOLIDOS_MOTOR_COLET_BOLSOES (

    interview__key VARCHAR(12),
    interview__id VARCHAR(32),

    R_LOCALIDADE__id INT,
    MOTOR_COLET_BOLSOES__id INT,

    QTD_MOTORISTAS_BL INT,
    QTD_COLETORES_BL INT


 );


 CREATE TABLE RESIDUOS_SOLIDOS_MOTOR_COLET_RSD(

    interview__key VARCHAR(12),
    interview__id VARCHAR(32),

    R_LOCALIDADE__id INT,
    MOTOR_COLET_RSD__id INT,

    QTD_MOTORISTAS_RSD INT,
    QTD_COLETORES_RSD INT

 );

 CREATE TABLE RESIDUOS_SOLIDOS_FREQ_COLETA_RSD (

    interview__key VARCHAR(12),
    interview__id VARCHAR(32),

    R_LOCALIDADE__id INT,
    FREQ_COLETA_RSD__id INT,

    LOCAL_BAIRRO_RSD__0 VARCHAR(140),
    LOCAL_BAIRRO_RSD__1 VARCHAR(140),
    LOCAL_BAIRRO_RSD__2 VARCHAR(140),
    LOCAL_BAIRRO_RSD__3 VARCHAR(140),
    LOCAL_BAIRRO_RSD__4 VARCHAR(140),
    LOCAL_BAIRRO_RSD__5 VARCHAR(140),
    LOCAL_BAIRRO_RSD__6 VARCHAR(140),
    LOCAL_BAIRRO_RSD__7 VARCHAR(140),
    LOCAL_BAIRRO_RSD__8 VARCHAR(140),
    LOCAL_BAIRRO_RSD__9 VARCHAR(140),
    LOCAL_BAIRRO_RSD__10 VARCHAR(140),
    LOCAL_BAIRRO_RSD__11 VARCHAR(140),
    LOCAL_BAIRRO_RSD__12 VARCHAR(140),
    LOCAL_BAIRRO_RSD__13 VARCHAR(140),
    LOCAL_BAIRRO_RSD__14 VARCHAR(140),
    LOCAL_BAIRRO_RSD__15 VARCHAR(140),
    LOCAL_BAIRRO_RSD__16 VARCHAR(140),
    LOCAL_BAIRRO_RSD__17 VARCHAR(140),
    LOCAL_BAIRRO_RSD__18 VARCHAR(140),
    LOCAL_BAIRRO_RSD__19 VARCHAR(140)

  );

  CREATE TABLE RESIDUOS_SOLIDOS_QTD_TT_RES_17_18 (

    interview__key VARCHAR(12),
    interview__id VARCHAR(32),

    R_LOCALIDADE__id INT,
    QTD_TT_RES_17_18__id INT,

    RESIDUOS_2017 VARCHAR(140),
    RESIDUOS_2018 VARCHAR(140)


);




CREATE TABLE RESIDUOS_SOLIDOS_INFOUNIDGERADORA (

    interview__key VARCHAR(12),
    interview__id VARCHAR(32),

    R_LOCALIDADE__id INT,
    R_UNI_GERADORA__id INT,
    INFOUNIDGERADORA__id INT,

    FORMA_EXEC_SERV__0 VARCHAR(140),
    FORMA_EXEC_SERV__1 VARCHAR(140),
    FORMA_EXEC_SERV__2 VARCHAR(140),
    FORMA_EXEC_SERV__3 VARCHAR(140),
    FORMA_EXEC_SERV__4 VARCHAR(140),

    OUTRA_FORMA_EXEC_SERV VARCHAR(140),

    QUEM_COLETA INT,

    IDENT_QUEM_COLETA VARCHAR(140),
    QUANT_COLETADA DECIMAL,

    ACOND_PERF_CORT INT,

    ACOND_RES_BIO__0 SMALLINT NULL,
    ACOND_RES_BIO__1 SMALLINT NULL,
    ACOND_RES_BIO__2 SMALLINT NULL,
    ACOND_RES_BIO__3 SMALLINT NULL,

    ACOND_DEMAIS_RES INT,

    DESC_DEMAIS_RES VARCHAR(140),
    FREQ_COLETA_EST_SAU VARCHAR(140),

    LOCAL_ARM_INT_EXT INT,

    DESC_LOC_ARM_EXT_INT VARCHAR(140),
    INSERIR_FOTO_DESC VARCHAR(140),

    COD_TRAT_DEST_RSS__1 SMALLINT NULL,
    COD_TRAT_DEST_RSS__2 SMALLINT NULL,
    COD_TRAT_DEST_RSS__3 SMALLINT NULL,
    COD_TRAT_DEST_RSS__4 SMALLINT NULL,
    COD_TRAT_DEST_RSS__5 SMALLINT NULL,
    COD_TRAT_DEST_RSS__6 SMALLINT NULL,
    COD_TRAT_DEST_RSS__7 SMALLINT NULL,
    COD_TRAT_DEST_RSS__8 SMALLINT NULL,
    COD_TRAT_DEST_RSS__9 SMALLINT NULL,
    COD_TRAT_DEST_RSS__10 SMALLINT NULL,
    COD_TRAT_DEST_RSS__11 SMALLINT NULL,
    COD_TRAT_DEST_RSS__12 SMALLINT NULL,
    COD_TRAT_DEST_RSS__13 SMALLINT NULL,
    COD_TRAT_DEST_RSS__14 SMALLINT NULL,
    COD_TRAT_DEST_RSS__15 SMALLINT NULL,
    COD_TRAT_DEST_RSS__16 SMALLINT NULL,

    ESP_COD_TRAT_DE__0 VARCHAR(140),
    ESP_COD_TRAT_DE__1 VARCHAR(140),
    ESP_COD_TRAT_DE__2 VARCHAR(140),
    ESP_COD_TRAT_DE__3 VARCHAR(140),
    ESP_COD_TRAT_DE__4 VARCHAR(140),
    ESP_COD_TRAT_DE__5 VARCHAR(140),
    ESP_COD_TRAT_DE__6 VARCHAR(140),
    ESP_COD_TRAT_DE__7 VARCHAR(140),
    ESP_COD_TRAT_DE__8 VARCHAR(140),
    ESP_COD_TRAT_DE__9 VARCHAR(140),
    ESP_COD_TRAT_DE__10 VARCHAR(140),
    ESP_COD_TRAT_DE__11 VARCHAR(140),
    ESP_COD_TRAT_DE__12 VARCHAR(140),
    ESP_COD_TRAT_DE__13 VARCHAR(140),
    ESP_COD_TRAT_DE__14 VARCHAR(140),
    ESP_COD_TRAT_DE__15 VARCHAR(140),
    ESP_COD_TRAT_DE__16 VARCHAR(140),
    ESP_COD_TRAT_DE__17 VARCHAR(140),
    ESP_COD_TRAT_DE__18 VARCHAR(140),
    ESP_COD_TRAT_DE__19 VARCHAR(140),
    ESP_COD_TRAT_DE__20 VARCHAR(140),
    ESP_COD_TRAT_DE__21 VARCHAR(140),
    ESP_COD_TRAT_DE__22 VARCHAR(140),
    ESP_COD_TRAT_DE__23 VARCHAR(140),
    ESP_COD_TRAT_DE__24 VARCHAR(140),
    ESP_COD_TRAT_DE__25 VARCHAR(140),
    ESP_COD_TRAT_DE__26 VARCHAR(140),
    ESP_COD_TRAT_DE__27 VARCHAR(140),
    ESP_COD_TRAT_DE__28 VARCHAR(140),
    ESP_COD_TRAT_DE__29 VARCHAR(140),
    ESP_COD_TRAT_DE__30 VARCHAR(140),
    ESP_COD_TRAT_DE__31 VARCHAR(140),
    ESP_COD_TRAT_DE__32 VARCHAR(140),
    ESP_COD_TRAT_DE__33 VARCHAR(140),
    ESP_COD_TRAT_DE__34 VARCHAR(140),
    ESP_COD_TRAT_DE__35 VARCHAR(140),
    ESP_COD_TRAT_DE__36 VARCHAR(140),
    ESP_COD_TRAT_DE__37 VARCHAR(140),
    ESP_COD_TRAT_DE__38 VARCHAR(140),
    ESP_COD_TRAT_DE__39 VARCHAR(140),
    ESP_COD_TRAT_DE__40 VARCHAR(140),
    ESP_COD_TRAT_DE__41 VARCHAR(140),
    ESP_COD_TRAT_DE__42 VARCHAR(140),
    ESP_COD_TRAT_DE__43 VARCHAR(140),
    ESP_COD_TRAT_DE__44 VARCHAR(140),
    ESP_COD_TRAT_DE__45 VARCHAR(140),
    ESP_COD_TRAT_DE__46 VARCHAR(140),
    ESP_COD_TRAT_DE__47 VARCHAR(140),
    ESP_COD_TRAT_DE__48 VARCHAR(140),
    ESP_COD_TRAT_DE__49 VARCHAR(140),
    ESP_COD_TRAT_DE__50 VARCHAR(140),
    ESP_COD_TRAT_DE__51 VARCHAR(140),
    ESP_COD_TRAT_DE__52 VARCHAR(140),
    ESP_COD_TRAT_DE__53 VARCHAR(140),
    ESP_COD_TRAT_DE__54 VARCHAR(140),
    ESP_COD_TRAT_DE__55 VARCHAR(140),
    ESP_COD_TRAT_DE__56 VARCHAR(140),
    ESP_COD_TRAT_DE__57 VARCHAR(140),
    ESP_COD_TRAT_DE__58 VARCHAR(140),
    ESP_COD_TRAT_DE__59 VARCHAR(140),
    ESP_COD_TRAT_DE__60 VARCHAR(140),
    ESP_COD_TRAT_DE__61 VARCHAR(140),
    ESP_COD_TRAT_DE__62 VARCHAR(140),
    ESP_COD_TRAT_DE__63 VARCHAR(140),
    ESP_COD_TRAT_DE__64 VARCHAR(140),
    ESP_COD_TRAT_DE__65 VARCHAR(140),
    ESP_COD_TRAT_DE__66 VARCHAR(140),
    ESP_COD_TRAT_DE__67 VARCHAR(140),
    ESP_COD_TRAT_DE__68 VARCHAR(140),
    ESP_COD_TRAT_DE__69 VARCHAR(140),
    ESP_COD_TRAT_DE__70 VARCHAR(140),
    ESP_COD_TRAT_DE__71 VARCHAR(140),
    ESP_COD_TRAT_DE__72 VARCHAR(140),
    ESP_COD_TRAT_DE__73 VARCHAR(140),
    ESP_COD_TRAT_DE__74 VARCHAR(140),
    ESP_COD_TRAT_DE__75 VARCHAR(140),
    ESP_COD_TRAT_DE__76 VARCHAR(140),
    ESP_COD_TRAT_DE__77 VARCHAR(140),
    ESP_COD_TRAT_DE__78 VARCHAR(140),
    ESP_COD_TRAT_DE__79 VARCHAR(140),
    ESP_COD_TRAT_DE__80 VARCHAR(140),
    ESP_COD_TRAT_DE__81 VARCHAR(140),
    ESP_COD_TRAT_DE__82 VARCHAR(140),
    ESP_COD_TRAT_DE__83 VARCHAR(140),
    ESP_COD_TRAT_DE__84 VARCHAR(140),
    ESP_COD_TRAT_DE__85 VARCHAR(140),
    ESP_COD_TRAT_DE__86 VARCHAR(140),
    ESP_COD_TRAT_DE__87 VARCHAR(140),
    ESP_COD_TRAT_DE__88 VARCHAR(140),
    ESP_COD_TRAT_DE__89 VARCHAR(140),
    ESP_COD_TRAT_DE__90 VARCHAR(140),
    ESP_COD_TRAT_DE__91 VARCHAR(140),
    ESP_COD_TRAT_DE__92 VARCHAR(140),
    ESP_COD_TRAT_DE__93 VARCHAR(140),
    ESP_COD_TRAT_DE__94 VARCHAR(140),
    ESP_COD_TRAT_DE__95 VARCHAR(140),
    ESP_COD_TRAT_DE__96 VARCHAR(140),
    ESP_COD_TRAT_DE__97 VARCHAR(140),
    ESP_COD_TRAT_DE__98 VARCHAR(140),
    ESP_COD_TRAT_DE__99 VARCHAR(140),
    ESP_COD_TRAT_DE__100 VARCHAR(140),
    ESP_COD_TRAT_DE__101 VARCHAR(140),
    ESP_COD_TRAT_DE__102 VARCHAR(140),
    ESP_COD_TRAT_DE__103 VARCHAR(140),
    ESP_COD_TRAT_DE__104 VARCHAR(140),
    ESP_COD_TRAT_DE__105 VARCHAR(140),
    ESP_COD_TRAT_DE__106 VARCHAR(140),
    ESP_COD_TRAT_DE__107 VARCHAR(140),
    ESP_COD_TRAT_DE__108 VARCHAR(140),
    ESP_COD_TRAT_DE__109 VARCHAR(140),
    ESP_COD_TRAT_DE__110 VARCHAR(140),
    ESP_COD_TRAT_DE__111 VARCHAR(140),
    ESP_COD_TRAT_DE__112 VARCHAR(140),
    ESP_COD_TRAT_DE__113 VARCHAR(140),
    ESP_COD_TRAT_DE__114 VARCHAR(140),
    ESP_COD_TRAT_DE__115 VARCHAR(140),
    ESP_COD_TRAT_DE__116 VARCHAR(140),
    ESP_COD_TRAT_DE__117 VARCHAR(140),
    ESP_COD_TRAT_DE__118 VARCHAR(140),
    ESP_COD_TRAT_DE__119 VARCHAR(140),
    ESP_COD_TRAT_DE__120 VARCHAR(140),
    ESP_COD_TRAT_DE__121 VARCHAR(140),
    ESP_COD_TRAT_DE__122 VARCHAR(140),
    ESP_COD_TRAT_DE__123 VARCHAR(140),
    ESP_COD_TRAT_DE__124 VARCHAR(140),
    ESP_COD_TRAT_DE__125 VARCHAR(140),
    ESP_COD_TRAT_DE__126 VARCHAR(140),
    ESP_COD_TRAT_DE__127 VARCHAR(140),
    ESP_COD_TRAT_DE__128 VARCHAR(140),
    ESP_COD_TRAT_DE__129 VARCHAR(140),
    ESP_COD_TRAT_DE__130 VARCHAR(140),
    ESP_COD_TRAT_DE__131 VARCHAR(140),
    ESP_COD_TRAT_DE__132 VARCHAR(140),
    ESP_COD_TRAT_DE__133 VARCHAR(140),
    ESP_COD_TRAT_DE__134 VARCHAR(140),
    ESP_COD_TRAT_DE__135 VARCHAR(140),
    ESP_COD_TRAT_DE__136 VARCHAR(140),
    ESP_COD_TRAT_DE__137 VARCHAR(140),
    ESP_COD_TRAT_DE__138 VARCHAR(140),
    ESP_COD_TRAT_DE__139 VARCHAR(140),
    ESP_COD_TRAT_DE__140 VARCHAR(140),
    ESP_COD_TRAT_DE__141 VARCHAR(140),
    ESP_COD_TRAT_DE__142 VARCHAR(140),
    ESP_COD_TRAT_DE__143 VARCHAR(140),
    ESP_COD_TRAT_DE__144 VARCHAR(140),
    ESP_COD_TRAT_DE__145 VARCHAR(140),
    ESP_COD_TRAT_DE__146 VARCHAR(140),
    ESP_COD_TRAT_DE__147 VARCHAR(140),
    ESP_COD_TRAT_DE__148 VARCHAR(140),
    ESP_COD_TRAT_DE__149 VARCHAR(140),
    ESP_COD_TRAT_DE__150 VARCHAR(140),
    ESP_COD_TRAT_DE__151 VARCHAR(140),
    ESP_COD_TRAT_DE__152 VARCHAR(140),
    ESP_COD_TRAT_DE__153 VARCHAR(140),
    ESP_COD_TRAT_DE__154 VARCHAR(140),
    ESP_COD_TRAT_DE__155 VARCHAR(140),
    ESP_COD_TRAT_DE__156 VARCHAR(140),
    ESP_COD_TRAT_DE__157 VARCHAR(140),
    ESP_COD_TRAT_DE__158 VARCHAR(140),
    ESP_COD_TRAT_DE__159 VARCHAR(140),
    ESP_COD_TRAT_DE__160 VARCHAR(140),
    ESP_COD_TRAT_DE__161 VARCHAR(140),
    ESP_COD_TRAT_DE__162 VARCHAR(140),
    ESP_COD_TRAT_DE__163 VARCHAR(140),
    ESP_COD_TRAT_DE__164 VARCHAR(140),
    ESP_COD_TRAT_DE__165 VARCHAR(140),
    ESP_COD_TRAT_DE__166 VARCHAR(140),
    ESP_COD_TRAT_DE__167 VARCHAR(140),
    ESP_COD_TRAT_DE__168 VARCHAR(140),
    ESP_COD_TRAT_DE__169 VARCHAR(140),
    ESP_COD_TRAT_DE__170 VARCHAR(140),
    ESP_COD_TRAT_DE__171 VARCHAR(140),
    ESP_COD_TRAT_DE__172 VARCHAR(140),
    ESP_COD_TRAT_DE__173 VARCHAR(140),
    ESP_COD_TRAT_DE__174 VARCHAR(140),
    ESP_COD_TRAT_DE__175 VARCHAR(140),
    ESP_COD_TRAT_DE__176 VARCHAR(140),
    ESP_COD_TRAT_DE__177 VARCHAR(140),
    ESP_COD_TRAT_DE__178 VARCHAR(140),
    ESP_COD_TRAT_DE__179 VARCHAR(140),
    ESP_COD_TRAT_DE__180 VARCHAR(140),
    ESP_COD_TRAT_DE__181 VARCHAR(140),
    ESP_COD_TRAT_DE__182 VARCHAR(140),
    ESP_COD_TRAT_DE__183 VARCHAR(140),
    ESP_COD_TRAT_DE__184 VARCHAR(140),
    ESP_COD_TRAT_DE__185 VARCHAR(140),
    ESP_COD_TRAT_DE__186 VARCHAR(140),
    ESP_COD_TRAT_DE__187 VARCHAR(140),
    ESP_COD_TRAT_DE__188 VARCHAR(140),
    ESP_COD_TRAT_DE__189 VARCHAR(140),
    ESP_COD_TRAT_DE__190 VARCHAR(140),
    ESP_COD_TRAT_DE__191 VARCHAR(140),
    ESP_COD_TRAT_DE__192 VARCHAR(140),
    ESP_COD_TRAT_DE__193 VARCHAR(140),
    ESP_COD_TRAT_DE__194 VARCHAR(140),
    ESP_COD_TRAT_DE__195 VARCHAR(140),
    ESP_COD_TRAT_DE__196 VARCHAR(140),
    ESP_COD_TRAT_DE__197 VARCHAR(140),
    ESP_COD_TRAT_DE__198 VARCHAR(140),
    ESP_COD_TRAT_DE__199 VARCHAR(140),

    LOCAL_TRAT_DEST_RSS VARCHAR(140),
    QUANT_IMG_RSS INT,

    RESP_INF_RSS__0 VARCHAR(140),
    RESP_INF_RSS__1 VARCHAR(140),
    RESP_INF_RSS__2 VARCHAR(140),
    RESP_INF_RSS__3 VARCHAR(140),
    RESP_INF_RSS__4 VARCHAR(140),
    RESP_INF_RSS__5 VARCHAR(140),
    RESP_INF_RSS__6 VARCHAR(140),
    RESP_INF_RSS__7 VARCHAR(140),
    RESP_INF_RSS__8 VARCHAR(140),
    RESP_INF_RSS__9 VARCHAR(140),
    RESP_INF_RSS__10 VARCHAR(140),
    RESP_INF_RSS__11 VARCHAR(140),
    RESP_INF_RSS__12 VARCHAR(140),
    RESP_INF_RSS__13 VARCHAR(140),
    RESP_INF_RSS__14 VARCHAR(140),

    OBS_RSS VARCHAR(300),

 );

---- ARQUIVO TABELAS(ROSTERS)

CREATE TABLE RESIDUOS_SOLIDOS_RESIDUOS_REC_ENV (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    RESIDUOS_REC_ENV__id INT,
    RECEBE_RESIDUOS_TP  VARCHAR (40) NULL,
    RECEBE_RESIDUOS_QTD VARCHAR (40) NULL,
    RESIDUOS_RECEB_2017 VARCHAR (40) NULL,
    RESIDUOS_RECEB_2018 VARCHAR (40) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_VEIC_EQUIP_PREF (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    VEIC_EQUIP_PREF__id INT,
    TP_CODIGO_6__1  VARCHAR (40) NULL,
    TP_CODIGO_6__2 VARCHAR (40) NULL,
    TP_CODIGO_6__3 VARCHAR (40) NULL,
    TP_CODIGO_6__4 VARCHAR (40) NULL,
    TP_CODIGO_6__5 VARCHAR (40) NULL,
    TP_CODIGO_6__6 VARCHAR (40) NULL,
    TP_CODIGO_6__7 VARCHAR (40) NULL,
    TP_CODIGO_6__8 VARCHAR (40) NULL,
    TP_CODIGO_6__9 VARCHAR (40) NULL,
    TP_CODIGO_6__10 VARCHAR (40) NULL,
    TP_CODIGO_6__11 VARCHAR (40) NULL,
    TP_CODIGO_6__12 VARCHAR (40) NULL,
    TP_CODIGO_6__13 VARCHAR (40) NULL,
    TP_CODIGO_6__14 VARCHAR (40) NULL,
    PREF_MARCA_VEIC_EQ VARCHAR (40) NULL,
    PREF_MODELO_VEIC_EQ VARCHAR (40) NULL,
    PREF_COMB_VEIC_EQ VARCHAR (40) NULL,
    PREF_ANO_VEIC_EQ INT NULL,
    PREF_CAPAC_VEIC_EQ  VARCHAR (40) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_VEIC_EQUIP_EMPRESA(
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    VEIC_EQUIP_EMPRESA__id INT,
    EMP_MARCA_VEIC_EQ VARCHAR (40) NULL,
    EMP_MODELO_VEIC_EQ VARCHAR (40) NULL,
    EMP_COMB_VEIC_EQ VARCHAR (40) NULL,
    EMP_ANO_VEIC_EQ INT NULL,
    EMP_CAPAC_VEIC_EQ VARCHAR (40) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_TRATAM_DISP_FINAL(
    interview__key VARCHAR(11) NOT NULL,
    interview__id VARCHAR(32) NOT NULL,
    R_LOCALIDADE__id SMALLINT NOT NULL,
    TRATAM_DISP_FINAL__id SMALLINT NOT NULL,
    ENDERECO_DISP_FINAL VARCHAR(150) NULL,
    COORD_DISP_FINAL__Latitude DOUBLE PRECISION NULL,
    COORD_DISP_FINAL__Longitude DOUBLE PRECISION NULL,
    COORD_DISP_FINAL__Accuracy DOUBLE PRECISION NULL,
    COORD_DISP_FINAL__Altitude DOUBLE PRECISION NULL,
    COORD_DISP_FINAL__Timestamp TIMESTAMP NULL,
    PROPRIET_DISP_FINAL__1 VARCHAR(150) NULL,
    PROPRIET_DISP_FINAL__2 VARCHAR(150) NULL,
    PROPRIET_DISP_FINAL__3 VARCHAR(150) NULL,
    PROPRIET_DISP_FINAL__4 VARCHAR(150) NULL,
    PROPRIET_DISP_FINAL__5 VARCHAR(150) NULL,
    PROPRIET_DISP_FINAL__9 VARCHAR(150) NULL,
    ANO_OPERACAO_DF TIMESTAMP NULL,
    OPERACAO_ENCERRADA SMALLINT NULL,
    ANO_ENCERRAMENTO TIMESTAMP NULL,
    TRAT_LIQ_PERCOLADOS SMALLINT,
    DESC_LIQ_PERCOLADOSV VARCHAR(150),
    RES_CHORUME SMALLINT NULL,
    IMAGEM_RES_CHORUME VARCHAR(150) NULL,
    POCOS_MONITORAMENTO SMALLINT NULL,
    ANAL_QUAL_AGUA VARCHAR(150) NULL,
    DISTANCIA_AERODROMO DECIMAL NULL,
    PROTECAO_CERCA SMALLINT NULL,
    CONSEVACAO_CERCA SMALLINT NULL,
    IMAGEM_CERCA VARCHAR(150) NULL,
    COMPAC_RES_DISPOST SMALLINT NULL,
    COBERTURA_RESIDUOS SMALLINT NULL,
    PERIODO_SECO VARCHAR(150) NULL,
    PERIODO_CHUVOSO VARCHAR(150) NULL,
    GRAMA_TALUDES SMALLINT NULL,
    MANUT_VIGILANCIA SMALLINT NULL,
    AREA_PROTECAO SMALLINT NULL,
    AREA_INUNDACAO SMALLINT NULL,
    EXISTENCIA_QUEIMADA SMALLINT NULL,
    PRESENCA_ANIMAIS SMALLINT NULL,
    PRESENCA_PASSAROS SMALLINT NULL,
    PRESENCA_VETORES SMALLINT NULL,
    CURSO_DAGUA DECIMAL NULL,
    NUCLEO_HABITACIONAL DECIMAL NULL,
    HABITACOES_ISOLADAS DECIMAL NULL,
    AREA_LIXAO SMALLINT NULL,
    RESIDENCIAS_LIXOES SMALLINT NULL,
    RES_PROX_LIXOES SMALLINT NULL,
    CATADORES_LOCAL SMALLINT NULL,
    NUMERO_CATADORES SMALLINT NULL,
    CATADORES_MENORES SMALLINT NULL,
    NUMERO_CAT_MENORES SMALLINT NULL,
    ORGAN_SOC_CATADORES__1 VARCHAR(150) NULL,
    ORGAN_SOC_CATADORES__2 VARCHAR(150) NULL,
    ORGAN_SOC_CATADORES__3 VARCHAR(150) NULL,
    ORGAN_SOC_CATADORES__4 VARCHAR(150) NULL,
    CATADORES_RESIDENCIA SMALLINT NULL,
    TEC_PROCESSAMENTO SMALLINT NULL,
    TIPO_PROCESSAMENTO__1 VARCHAR(150) NULL,
    TIPO_PROCESSAMENTO__2 VARCHAR(150) NULL,
    TIPO_PROCESSAMENTO__3 VARCHAR(150) NULL,
    TIPO_PROCESSAMENTO__4 VARCHAR(150) NULL,
    TIPO_PROCESSAMENTO__5 VARCHAR(150) NULL,
    TIPO_PROCESSAMENTO__6 VARCHAR(150) NULL,
    TIPO_PROCESSAMENTO__7 VARCHAR(150) NULL,
    TIPO_PROCESSAMENTO__8 VARCHAR(150) NULL,
    TIPO_PROCESSAMENTO__9 VARCHAR(150) NULL,
    TIPO_PROCESSAMENTO__10 VARCHAR(150) NULL,
    TIPO_PROCESSAMENTO__11 VARCHAR(150) NULL,
    TIPO_PROCESSAMENTO__12 VARCHAR(150) NULL,
    TIPO_PROCESSAMENTO__13 VARCHAR(150) NULL,
    TIPO_PROCESSAMENTO__14 VARCHAR(150) NULL,
    TIPO_PROCESSAMENTO__15 VARCHAR(150) NULL,
    TIPO_PROCESSAMENTO__16 VARCHAR(150) NULL,
    GERACAO_EFLUENTES SMALLINT NULL,
    SISTEMA_TRATAMENTO SMALLINT NULL,
    GERACAO_GASES SMALLINT NULL,
    EQUIPAMENTO_CONT VARCHAR(150) NULL,
    RESIDUOS_PROCESSO SMALLINT NULL,
    LOCAL_DISPOSICAO VARCHAR(150) NULL,
    UNIDADES_EXISTENTES VARCHAR(150) NULL,
    IMAGENS_PROCES VARCHAR(150) NULL,
    RESP_INFORMACOES__0 SMALLINT NULL,
    RESP_INFORMACOES__1 SMALLINT NULL,
    RESP_INFORMACOES__2 SMALLINT NULL,
    RESP_INFORMACOES__3 SMALLINT NULL,
    RESP_INFORMACOES__4 SMALLINT NULL,
    RESP_INFORMACOES__5 SMALLINT NULL,
    RESP_INFORMACOES__6 SMALLINT NULL,
    RESP_INFORMACOES__7 SMALLINT NULL,
    RESP_INFORMACOES__8 SMALLINT NULL,
    RESP_INFORMACOES__9 SMALLINT NULL,
    RESP_INFORMACOES__10 SMALLINT NULL,
    RESP_INFORMACOES__11 SMALLINT NULL,
    RESP_INFORMACOES__12 SMALLINT NULL,
    RESP_INFORMACOES__13 SMALLINT NULL,
    RESP_INFORMACOES__14 SMALLINT NULL,
    RESP_INFORMACOES__15 SMALLINT NULL,
    RESP_INFORMACOES__16 SMALLINT NULL,
    RESP_INFORMACOES__17 SMALLINT NULL,
    RESP_INFORMACOES__18 SMALLINT NULL,
    RESP_INFORMACOES__19 SMALLINT NULL,
    OBERSVACOES VARCHAR(300) NULL
);



CREATE TABLE RESIDUOS_SOLIDOS_R_CUSTO_SERV_LP (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_CUSTO_SERV_LP__id INT,
    PES_OCUP_17 VARCHAR (40) NULL,
    PES_OCUP_18 VARCHAR (40) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_R_EQUIP_FERRAM (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_EQUIP_FERRAM__id INT,
    EQUIP_FER_17 VARCHAR (40) NULL,
    EQUIP_FER_18 VARCHAR (40) NULL
);


CREATE TABLE RESIDUOS_SOLIDOS_R_EXISTENCIA (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    TRATAM_DISP_FINAL__id INT,
    R_EXISTENCIA__id INT,
    INSTALACOES_ADM INT NULL,
    CONSERVACAO_ADM INT NULL,
    IMG_EXISTENCIA_CONSERV VARCHAR (40) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_R_GASTOS_PESSOAL (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_GASTOS_PESSOAL__id INT,
    GASTOS_PES_17 VARCHAR (40) NULL,
    GASTOS_PES_18 VARCHAR (40) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_R_LOCALIDADE (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    LOC_RESI VARCHAR (40),
    TIP_RES_PRO_LOC__1 VARCHAR (40) NULL,
    TIP_RES_PRO_LOC__2 VARCHAR (40) NULL,
    TIP_RES_PRO_LOC__3 VARCHAR (40) NULL,
    TIP_RES_PRO_LOC__4 VARCHAR (40) NULL,
    TIP_RES_PRO_LOC__5 VARCHAR (40) NULL,
    TIP_RES_PRO_LOC__6 VARCHAR (40) NULL,
    TIP_RES_PRO_LOC__7 VARCHAR (40) NULL,
    TIP_RES_PRO_LOC__8 VARCHAR (40) NULL,
    TIP_RES_PRO_LOC__9 VARCHAR (40) NULL,
    PLANO_GERENCIA INT NULL,
    ANEXO_PLANO_GERENC VARCHAR (40) NULL,
    RESP_SERVICO INT NULL,
    PRESTACAO_SERV__1 VARCHAR (40) NULL,
    PRESTACAO_SERV__2 VARCHAR (40) NULL,
    NOME_TERCEIRIZADA VARCHAR (40) NULL,
    RESP_SERVICO_2 INT NULL,
    NOME_EMPRESA VARCHAR (40) NULL,
    ESPEC_RESPONS VARCHAR (40) NULL,
    PADRONIZACAO_COLETA INT NULL,
    PADRONIZACAO_ACOND INT NULL,
    ACOND_RES_FONTE__1 VARCHAR (40) NULL,
    ACOND_RES_FONTE__2 VARCHAR (40) NULL,
    ACOND_RES_FONTE__3 VARCHAR (40) NULL,
    ACOND_RES_FONTE__4 VARCHAR (40) NULL,
    ACOND_RES_FONTE__5 VARCHAR (40) NULL,
    ESP_PAD_RES_FONTE VARCHAR (40) NULL,
    DISTINCAO_RES_FONTE__1 VARCHAR (40) NULL,
    DISTINCAO_RES_FONTE__2 VARCHAR (40) NULL,
    DISTINCAO_RES_FONTE__3 VARCHAR (40) NULL,
    DISTINCAO_RES_FONTE__4 VARCHAR (40) NULL,
    ESPEC_DIST_RES VARCHAR (40) NULL,
    FREQ_VERIFICACAO__1 VARCHAR (40) NULL,
    FREQ_VERIFICACAO__2 VARCHAR (40) NULL,
    FREQ_VERIFICACAO__3 VARCHAR (40) NULL,
    FREQ_VERIFICACAO__4 VARCHAR (40) NULL,
    ESP_FREQ_VERIF VARCHAR (40) NULL,
    QTD_VEIC_COL_RSD VARCHAR (40) NULL,
    PREF_COLETA_RSD VARCHAR (40) NULL,
    EMPRESA_COLETA_RSD VARCHAR (40) NULL,
    ORGANIZACAO_COLETA INT NULL,
    ESPEC_ORGANIZ_COL VARCHAR (40) NULL,
    QTD_TT_MOTORISTAS_RSD INT NULL,
    QTD_TT_COLETORES_RSD INT NULL,
    QTD_TT_MOTORISTAS_BL INT NULL,
    QTD_TT_COLETORES_BL INT NULL,
    ENV_OU_RECE_RESI_MUN INT NULL,
    ENV_RECE_RESI_MUN__1 INT NULL,
    ENV_RECE_RESI_MUN__2 INT NULL,
    DESTINO_RES_ENVIADOS VARCHAR (40) NULL,
    UNID_TRANSFERENCIA INT NULL,
    TP_UNID_TRANSF_COD_5__1 VARCHAR (40) NULL,
    TP_UNID_TRANSF_COD_5__2 VARCHAR (40) NULL,
    TP_UNID_TRANSF_COD_5__3 VARCHAR (40) NULL,
    LOC_UNID_TRANSFER_1 VARCHAR (40) NULL,
    LOC_UNID_TRANSFER_2__Latitude DOUBLE PRECISION NULL,
    LOC_UNID_TRANSFER_2__Longitude DOUBLE PRECISION NULL,
    LOC_UNID_TRANSFER_2__Accuracy DOUBLE PRECISION NULL,
    LOC_UNID_TRANSFER_2__Altitude DOUBLE PRECISION NULL,
    LOC_UNID_TRANSFER_2__Timestamp TIMESTAMP NULL,
    ACONDICIONAMENTO_TP INT NULL,
    ESP_ACONDICIONAMENTO  VARCHAR (40) NULL,
    INFRAEST_TRANSFER__1 VARCHAR (40) NULL,
    INFRAEST_TRANSFER__2 VARCHAR (40) NULL,
    INFRAEST_TRANSFER__3 VARCHAR (40) NULL,
    INFRAEST_TRANSFER__4 VARCHAR (40) NULL,
    ESPEC_INFRAEST VARCHAR (40) NULL,
    CAP_ARMAZ_VOLUME DECIMAL NULL,
    CAP_ARMAZ_PESO DECIMAL NULL,
    COMPACT_RESIDUO INT NULL,
    FREQ_TRANSPORTE INT NULL,
    ESPEC_FREQ_TRANSP  VARCHAR (40) NULL,
    VOLUME_TRANSPORTADO DECIMAL NULL,
    DESC_MAQUINARIOS_ENV  VARCHAR (40) NULL,
    PRESENCA_CATADORES INT NULL,
    IMAGENS_CATADORES INT NULL,
    TRAT_DEST_FIN__1 VARCHAR (40) NULL,
    TRAT_DEST_FIN__2 VARCHAR (40) NULL,
    TRAT_DEST_FIN__3 VARCHAR (40) NULL,
    TRAT_DEST_FIN__4 VARCHAR (40) NULL,
    TRAT_DEST_FIN__5 VARCHAR (40) NULL,
    TRAT_DEST_FIN__6 VARCHAR (40) NULL,
    TRAT_DEST_FIN__7 VARCHAR (40) NULL,
    TRAT_DEST_FIN__8 VARCHAR (40) NULL,
    TRAT_DEST_FIN__9 VARCHAR (40) NULL,
    TRAT_DEST_FIN__10 VARCHAR (40) NULL,
    TRAT_DEST_FIN__11 VARCHAR (40) NULL,
    TRAT_DEST_FIN__12 VARCHAR (40) NULL,
    TRAT_DEST_FIN__13 VARCHAR (40) NULL,
    TRAT_DEST_FIN__14 VARCHAR (40) NULL,
    TRAT_DEST_FIN__15 VARCHAR (40) NULL,
    TRAT_DEST_FIN__16 VARCHAR (40) NULL,
    SETOR_GERADOR__0 VARCHAR (40) NULL,
    SETOR_GERADOR__1 VARCHAR (40) NULL,
    FORMAS_REAPROV__0 VARCHAR (40) NULL,
    FORMAS_REAPROV__1 VARCHAR (40) NULL,
    FORMAS_REAPROV__2 VARCHAR (40) NULL,
    FORMAS_REAPROV__3 VARCHAR (40) NULL,
    FORMAS_REAPROV__4 VARCHAR (40) NULL,
    FORMAS_REAPROV__5 VARCHAR (40) NULL,
    DESC_FORMA_REAPROV VARCHAR (40) NULL,
    SEGREGACAO_MATERIAIS INT NULL,
    COORD_RCC VARCHAR (40) NULL,
    SERV_PUB_COL_RCC INT NULL,
    COMO_POPUL_ACESSO INT NULL,
    OUTRA_POPUL_ACESSO VARCHAR (40) NULL,
    FREQ_COLETA_RCC VARCHAR (40) NULL,
    REAL_PREST_SERV_RCC INT NULL,
    QUANT_COLET_RCC VARCHAR (40) NULL,
    OUTRO_SERV_RCC__0 VARCHAR (40) NULL,
    OUTRO_SERV_RCC__1 VARCHAR (40) NULL,
    OUTRO_SERV_RCC__2 VARCHAR (40) NULL,
    OUTRO_SERV_RCC__3 VARCHAR (40) NULL,
    OUTRO_SERV_RCC__4 VARCHAR (40) NULL,
    OUTRO_PREST_SERV_RCC VARCHAR (40) NULL,
    QUANT_IMG_RCC INT NULL,
    RESP_INF_RCC__0 VARCHAR (40) NULL,
    RESP_INF_RCC__1 VARCHAR (40) NULL,
    RESP_INF_RCC__2 VARCHAR (40) NULL,
    RESP_INF_RCC__3 VARCHAR (40) NULL,
    RESP_INF_RCC__4 VARCHAR (40) NULL,
    RESP_INF_RCC__5 VARCHAR (40) NULL,
    RESP_INF_RCC__6 VARCHAR (40) NULL,
    RESP_INF_RCC__7 VARCHAR (40) NULL,
    RESP_INF_RCC__8 VARCHAR (40) NULL,
    RESP_INF_RCC__9 VARCHAR (40) NULL,
    RESP_INF_RCC__10 VARCHAR (40) NULL,
    RESP_INF_RCC__11 VARCHAR (40) NULL,
    RESP_INF_RCC__12 VARCHAR (40) NULL,
    RESP_INF_RCC__13 VARCHAR (40) NULL,
    RESP_INF_RCC__14 VARCHAR (40) NULL,
    OBS_RCC VARCHAR (40) NULL,
    SERV_LIMP_PBC_URB__1 VARCHAR (40) NULL,
    SERV_LIMP_PBC_URB__2 VARCHAR (40) NULL,
    SERV_LIMP_PBC_URB__3 VARCHAR (40) NULL,
    SERV_LIMP_PBC_URB__4 VARCHAR (40) NULL,
    SERV_LIMP_PBC_URB__5 VARCHAR (40) NULL,
    SERV_LIMP_PBC_URB__6 VARCHAR (40) NULL,
    SERV_LIMP_PBC_URB__7 VARCHAR (40) NULL,
    SERV_LIMP_PBC_URB__8 VARCHAR (40) NULL,
    SERV_LIMP_PBC_URB__9 VARCHAR (40) NULL,
    SERV_LIMP_PBC_URB__10 VARCHAR (40) NULL,
    SERV_LIMP_PBC_URB__11 VARCHAR (40) NULL,
    SERV_LIMP_PBC_URB__12 VARCHAR (40) NULL,
    SERV_LIMP_PBC_URB__13 VARCHAR (40) NULL,
    SERV_LIMP_PBC_URB__14 VARCHAR (40) NULL,
    SERV_LIMP_PBC_URB__15 VARCHAR (40) NULL,
    SERV_LIMP_PBC_URB__16 VARCHAR (40) NULL,
    SERV_LIMP_PBC_URB__17 VARCHAR (40) NULL,
    UNID_TRANSP_RST INT NULL,
    SIST_COL_ESP_RST INT NULL,
    DESC_SIST_COL_RST VARCHAR (40) NULL,
    SIST_TRAT_ESP_RST INT NULL,
    DESC_SIST_TRAT_RST INT NULL,
    SIST_DEST_ESP_RST INT NULL,
    DESC_SIST_DEST_ESP_RST VARCHAR (40) NULL,
    DEST_CONJ_RES_DOM INT NULL,
    DESC_OUTRO_DEST_RST  VARCHAR (40) NULL,
    QTDE_FOTO_RST INT NULL,
    RESP_INF_RST__0 VARCHAR (40) NULL,
    RESP_INF_RST__1 VARCHAR (40) NULL,
    RESP_INF_RST__2 VARCHAR (40) NULL,
    RESP_INF_RST__3 VARCHAR (40) NULL,
    RESP_INF_RST__4 VARCHAR (40) NULL,
    RESP_INF_RST__5 VARCHAR (40) NULL,
    RESP_INF_RST__6 VARCHAR (40) NULL,
    RESP_INF_RST__7 VARCHAR (40) NULL,
    RESP_INF_RST__8 VARCHAR (40) NULL,
    RESP_INF_RST__9 VARCHAR (40) NULL,
    RESP_INF_RST__10 VARCHAR (40) NULL,
    RESP_INF_RST__11 VARCHAR (40) NULL,
    RESP_INF_RST__12 VARCHAR (40) NULL,
    RESP_INF_RST__13 VARCHAR (40) NULL,
    RESP_INF_RST__14 VARCHAR (40) NULL,
    OBS_RST VARCHAR (40) NULL,
    QUANT_COM_LOC_RSC VARCHAR (40) NULL,
    PL_GER_RES_RSC INT NULL,
    LIC_AMB_RSC INT NULL,
    ORG_LIC_AMB_RSC INT NULL,
    QUANT_PRIN_RES_GER_RSC INT NULL,
    FONTE_RES_GER_RSC  VARCHAR (40) NULL,
    CONHEC_QUANT_RES_RSC INT NULL,
    QUANT_RES_GER_RSC INT NULL,
    EMP_COLETORA_RSC INT NULL,
    EMP_CONT_COL_RSC VARCHAR (40) NULL,
    OUTRO_FORM_COLETA_RSC VARCHAR (40) NULL,
    RES_PERIG_RSC INT NULL,
    SEG_RES_PER_RSC INT NULL,
    GER_COM_DOM_RSC INT NULL,
    QUANT_IMG_RSC INT NULL,
    LOC_DESC_TRAT_RSC__1 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSC__2 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSC__3 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSC__4 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSC__5 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSC__6 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSC__7 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSC__8 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSC__9 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSC__10 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSC__11 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSC__12 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSC__13 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSC__14 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSC__15 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSC__16 VARCHAR (40) NULL,
    RESP_INF_RSC__0 VARCHAR (40) NULL,
    RESP_INF_RSC__1 VARCHAR (40) NULL,
    RESP_INF_RSC__2 VARCHAR (40) NULL,
    RESP_INF_RSC__3 VARCHAR (40) NULL,
    RESP_INF_RSC__4 VARCHAR (40) NULL,
    RESP_INF_RSC__5 VARCHAR (40) NULL,
    RESP_INF_RSC__6 VARCHAR (40) NULL,
    RESP_INF_RSC__7 VARCHAR (40) NULL,
    RESP_INF_RSC__8 VARCHAR (40) NULL,
    RESP_INF_RSC__9 VARCHAR (40) NULL,
    RESP_INF_RSC__10 VARCHAR (40) NULL,
    RESP_INF_RSC__11 VARCHAR (40) NULL,
    RESP_INF_RSC__12 VARCHAR (40) NULL,
    RESP_INF_RSC__13 VARCHAR (40) NULL,
    RESP_INF_RSC__14 VARCHAR (40) NULL,
    OBS_RSC VARCHAR (40) NULL,
    QUANT_INDUS_LOC_RSI VARCHAR (40) NULL,
    LIC_AMB_RSI INT NULL,
    ORG_LIC_AMB_RSI INT NULL,
    PLANO_GER_RES_RSI INT NULL,
    QUANT_PRIN_RES_GER_RSI VARCHAR (40) NULL,
    FONTE_RES_GER_RSI VARCHAR (40) NULL,
    CONHEC_QUANT_RES_RSI VARCHAR (40) NULL,
    QUANT_RES_GER_RSI INT NULL,
    EMP_COLETORA_RSI VARCHAR (40) NULL,
    RES_PERIG_RSI VARCHAR (40) NULL,
    SEG_RES_PER_RSI VARCHAR (40) NULL,
    QUANT_IMG_RSI INT NULL,
    LOC_DESC_TRAT_RSI__1 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSI__2 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSI__3 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSI__4 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSI__5 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSI__6 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSI__7 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSI__8 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSI__9 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSI__10 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSI__11 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSI__12 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSI__13 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSI__14 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSI__15 VARCHAR (40) NULL,
    LOC_DESC_TRAT_RSI__16 VARCHAR (40) NULL,
    RESP_INF_RSI__0 VARCHAR (40) NULL,
    RESP_INF_RSI__1 VARCHAR (40) NULL,
    RESP_INF_RSI__2 VARCHAR (40) NULL,
    RESP_INF_RSI__3 VARCHAR (40) NULL,
    RESP_INF_RSI__4 VARCHAR (40) NULL,
    RESP_INF_RSI__5 VARCHAR (40) NULL,
    RESP_INF_RSI__6 VARCHAR (40) NULL,
    RESP_INF_RSI__7 VARCHAR (40) NULL,
    RESP_INF_RSI__8 VARCHAR (40) NULL,
    RESP_INF_RSI__9 VARCHAR (40) NULL,
    RESP_INF_RSI__10 VARCHAR (40) NULL,
    RESP_INF_RSI__11 VARCHAR (40) NULL,
    RESP_INF_RSI__12 VARCHAR (40) NULL,
    RESP_INF_RSI__13 VARCHAR (40) NULL,
    RESP_INF_RSI__14 VARCHAR (40) NULL,
    OBS_RSI VARCHAR (40) NULL,
    IND_RES_GER_LOC__1 VARCHAR (40) NULL,
    IND_RES_GER_LOC__2 VARCHAR (40) NULL,
    IND_RES_GER_LOC__3 VARCHAR (40) NULL,
    IND_RES_GER_LOC__4 VARCHAR (40) NULL,
    IND_RES_GER_LOC__5 VARCHAR (40) NULL,
    IND_RES_GER_LOC__6 VARCHAR (40) NULL,
    LOC_COL_SELET INT NULL,
    SIT_COL_SELET INT NULL,
    PLAN_COLE_SET TEXT NULLL,
    MAP_FREQUEN VARCHAR (40) NULL,
    ITINERA_COLE_SELET VARCHAR (120) NULL,
    INIC_PRO_COLE__1 VARCHAR (40) NULL,
    INIC_PRO_COLE__2 VARCHAR (40) NULL,
    INIC_PRO_COLE__3 VARCHAR (40) NULL,
    INIC_PRO_COLE__4 VARCHAR (40) NULL,
    INIC_PRO_COLE__5 VARCHAR (40) NULL,
    QUEM_FAZ_COLET_SELT__0 VARCHAR (40) NULL,
    QUEM_FAZ_COLET_SELT__1 VARCHAR (40) NULL,
    QUEM_FAZ_COLET_SELT__2 VARCHAR (40) NULL,
    QUEM_FAZ_COLET_SELT__3 VARCHAR (40) NULL,
    QUEM_FAZ_COLET_SELT__4 VARCHAR (40) NULL,
    QUEM_FAZ_COLET_SELT__5 VARCHAR (40) NULL,
    QUEM_FAZ_COLET_SELT__6 VARCHAR (40) NULL,
    QUEM_FAZ_COLET_SELT__7 VARCHAR (40) NULL,
    QUEM_FAZ_COLET_SELT__8 VARCHAR (40) NULL,
    QUEM_FAZ_COLET_SELT__9 VARCHAR (40) NULL,
    QUEM_FAZ_COLET_SELT__10 VARCHAR (40) NULL,
    QUEM_FAZ_COLET_SELT__11 VARCHAR (40) NULL,
    QUEM_FAZ_COLET_SELT__12 VARCHAR (40) NULL,
    QUEM_FAZ_COLET_SELT__13 VARCHAR (40) NULL,
    QUEM_FAZ_COLET_SELT__14 VARCHAR (40) NULL,
    EXIST_CAMP_COM_LIXO INT NULL,
    FORM_EX_COLE_SELT__1 VARCHAR (40) NULL,
    FORM_EX_COLE_SELT__2 VARCHAR (40) NULL,
    FORM_EX_COLE_SELT__3 VARCHAR (40) NULL,
    ESPE_FORM_COLE_SELT VARCHAR (40) NULL,
    INF_RES_COBER INT NULL,
    INFO_RESI_COBERTAS VARCHAR (40) NULL,
    INF_PES_RES_COBER INT NULL,
    INFO_PES_RES_COBER VARCHAR (40) NULL,
    QUAN_MAT_REC_COLET INT NULL,
    INFO_QUANT_REC_COLET VARCHAR (40) NULL,
    PART_POPU_COLE_SELT INT NULL,
    ASS_COOP_CAT__1 VARCHAR (40) NULL,
    ASS_COOP_CAT__2 VARCHAR (40) NULL,
    ASS_COOP_CAT__3 VARCHAR (40) NULL,
    ASS_COOP_CAT_ENTI__0 VARCHAR (40) NULL,
    ASS_COOP_CAT_ENTI__1 VARCHAR (40) NULL,
    ASS_COOP_CAT_ENTI__2 VARCHAR (40) NULL,
    ASS_COOP_CAT_ENTI__3 VARCHAR (40) NULL,
    ASS_COOP_CAT_ENTI__4 VARCHAR (40) NULL,
    ASS_COOP_CAT_ENTI__5 VARCHAR (40) NULL,
    ASS_COOP_CAT_ENTI__6 VARCHAR (40) NULL,
    ASS_COOP_CAT_ENTI__7 VARCHAR (40) NULL,
    ASS_COOP_CAT_ENTI__8 VARCHAR (40) NULL,
    ASS_COOP_CAT_ENTI__9 VARCHAR (40) NULL,
    ASS_COOP_CAT_ENTI__10 VARCHAR (40) NULL,
    ASS_COOP_CAT_ENTI__11 VARCHAR (40) NULL,
    ASS_COOP_CAT_ENTI__12 VARCHAR (40) NULL,
    ASS_COOP_CAT_ENTI__13 VARCHAR (40) NULL,
    ASS_COOP_CAT_ENTI__14 VARCHAR (40) NULL,
    INFR_COLET_SELET__1 VARCHAR (40) NULL,
    INFR_COLET_SELET__2 VARCHAR (40) NULL,
    INFR_COLET_SELET__3 VARCHAR (40) NULL,
    TRIA_MAT_DEST_FI INT NULL,
    MAT_REC_TRIADOS__1 VARCHAR (40) NULL,
    MAT_REC_TRIADOS__2 VARCHAR (40) NULL,
    MAT_REC_TRIADOS__3 VARCHAR (40) NULL,
    MAT_REC_TRIADOS__4 VARCHAR (40) NULL,
    MAT_REC_TRIADOS__5 VARCHAR (40) NULL,
    MAT_REC_TRIADOS__6 VARCHAR (40) NULL,
    MAT_REC_TRIADOS__7 VARCHAR (40) NULL,
    MAT_REC_TRIADOS__8 VARCHAR (40) NULL,
    MAT_REC_TRIADOS__9 VARCHAR (40) NULL,
    MAT_REC_TRIADOS__10 VARCHAR (40) NULL,
    MAT_REC_TRIADOS__11 VARCHAR (40) NULL,
    MAT_REC_TRIADOS__12 VARCHAR (40) NULL,
    MAT_REC_TRIADOS__13 VARCHAR (40) NULL,
    MAT_REC_TRIADOS__14 VARCHAR (40) NULL,
    ESPEC_MAT_REC_TRIA VARCHAR (40) NULL,
    AREA_ABRAN_COLE_SEL INT NULL,
    LISTAR_BAIRR_SELEC__0 VARCHAR (40) NULL,
    LISTAR_BAIRR_SELEC__1 VARCHAR (40) NULL,
    LISTAR_BAIRR_SELEC__2 VARCHAR (40) NULL,
    LISTAR_BAIRR_SELEC__3 VARCHAR (40) NULL,
    LISTAR_BAIRR_SELEC__4 VARCHAR (40) NULL,
    LISTAR_BAIRR_SELEC__5 VARCHAR (40) NULL,
    LISTAR_BAIRR_SELEC__6 VARCHAR (40) NULL,
    LISTAR_BAIRR_SELEC__7 VARCHAR (40) NULL,
    LISTAR_BAIRR_SELEC__8 VARCHAR (40) NULL,
    LISTAR_BAIRR_SELEC__9 VARCHAR (40) NULL,
    LISTAR_BAIRR_SELEC__10 VARCHAR (40) NULL,
    LISTAR_BAIRR_SELEC__11 VARCHAR (40) NULL,
    LISTAR_BAIRR_SELEC__12 VARCHAR (40) NULL,
    LISTAR_BAIRR_SELEC__13 VARCHAR (40) NULL,
    LISTAR_BAIRR_SELEC__14 VARCHAR (40) NULL,
    PRINC_PART_COLE_SEL__1 VARCHAR (40) NULL,
    PRINC_PART_COLE_SEL__2 VARCHAR (40) NULL,
    PRINC_PART_COLE_SEL__3 VARCHAR (40) NULL,
    PRINC_PART_COLE_SEL__4 VARCHAR (40) NULL,
    PRINC_PART_COLE_SEL__5 VARCHAR (40) NULL,
    PRINC_PART_COLE_SEL__6 VARCHAR (40) NULL,
    PRINC_PART_COLE_SEL__7 VARCHAR (40) NULL,
    PRINC_PART_COLE_SEL__8 VARCHAR (40) NULL,
    IND_ARE_APLIC_RECUR__1 VARCHAR (40) NULL,
    IND_ARE_APLIC_RECUR__2 VARCHAR (40) NULL,
    IND_ARE_APLIC_RECUR__3 VARCHAR (40) NULL,
    IND_ARE_APLIC_RECUR__4 VARCHAR (40) NULL,
    IND_ARE_APLIC_RECUR__5 VARCHAR (40) NULL,
    IND_ARE_APLIC_RECUR__6 VARCHAR (40) NULL,
    RECUR_PROVE_COL_SELT VARCHAR (40) NULL,
    PRIN_RECE_FIN_RECI__1 VARCHAR (40) NULL,
    PRIN_RECE_FIN_RECI__2 VARCHAR (40) NULL,
    PRIN_RECE_FIN_RECI__3 VARCHAR (40) NULL,
    PRIN_RECE_FIN_RECI__4 VARCHAR (40) NULL,
    PRIN_RECE_FIN_RECI__5 VARCHAR (40) NULL,
    PRIN_RECE_FIN_RECI__6 VARCHAR (40) NULL,
    PRIN_RECE_FIN_RECI__7 VARCHAR (40) NULL,
    PRIN_RECE_FIN_RECI__8 VARCHAR (40) NULL,
    PRIN_RECE_FIN_RECI__9 VARCHAR (40) NULL,
    CIT_PRIN_RECEP_FIN_C VARCHAR (40) NULL,
    CT_PRIN_RCPT_F_ENT VARCHAR (40) NULL,
    CT_PRIN_RCPT_F_IND VARCHAR (40) NULL,
    CT_PRIN_RCPT_F_DEP VARCHAR (40) NULL,
    ESP_QUAIS_OTRS2 VARCHAR (40) NULL,
    QTD_FT_OBS_CLT_SLTV VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__0 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__1 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__2 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__3 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__4 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__5 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__6 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__7 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__8 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__9 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__10 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__11 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__12 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__13 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__14 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__15 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__16 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__17 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__18 VARCHAR (40) NULL,
    RESP_INFO_CLT_SLTV__19 VARCHAR (40) NULL,
    OBS_CLT_SLTV_TRIA VARCHAR (40) NULL
);


CREATE TABLE RESIDUOS_SOLIDOS_R_OUTROS_CUSTOS (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_OUTROS_CUSTOS__id INT,
    OUTROS_CUST_17 VARCHAR (40),
    OUTROS_CUST_18 VARCHAR (40)
);

CREATE TABLE RESIDUOS_SOLIDOS_R_IMG_PROCESSAMENTO (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    TRATAM_DISP_FINAL__id INT,
    R_IMG_PROCESSAMENTO__id INT,
    IMG_PROCESSAMENTO VARCHAR (120) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_ROST_SALVADOR (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    ROST_SERVI_LIMP_PUB__id INT,
    ROST_SALVADOR__id INT,
    DENOM_EMPR_CONTT VARCHAR (40) NULL,
    FREQ_EXE_2017 VARCHAR (40) NULL,
    FREQ_EXE_2018 VARCHAR (40) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_ROST_SERVI_LIMP_PUB (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    ROST_SERVI_LIMP_PUB__id INT,
    EXE_SERVI__1 VARCHAR (40) NULL,
    EXE_SERVI__2 VARCHAR (40) NULL,
    TIP_VEICU_CLTR__1 VARCHAR (40) NULL,
    TIP_VEICU_CLTR__2 VARCHAR (40) NULL,
    TIP_VEICU_CLTR__3 VARCHAR (40) NULL,
    TIP_VEICU_CLTR__4 VARCHAR (40) NULL,
    TIP_VEICU_CLTR__5 VARCHAR (40) NULL,
    TIP_VEICU_CLTR__6 VARCHAR (40) NULL,
    TIP_VEICU_CLTR__7 VARCHAR (40) NULL,
    TIP_VEICU_CLTR__8 VARCHAR (40) NULL,
    TIP_VEICU_CLTR__9 VARCHAR (40) NULL,
    TIP_VEICU_CLTR__10 VARCHAR (40) NULL,
    TIP_VEICU_CLTR__11 VARCHAR (40) NULL,
    TIP_VEICU_CLTR__12 VARCHAR (40) NULL,
    TIP_VEICU_CLTR__13 VARCHAR (40) NULL,
    TIP_VEICU_CLTR__14 VARCHAR (40) NULL,
    COMO_CLT__1 VARCHAR (40) NULL,
    COMO_CLT__2 VARCHAR (40) NULL,
    COMO_CLT__3 VARCHAR (40) NULL,
    COMO_CLT__4 VARCHAR (40) NULL,
    QUAIS_OUT_FORM_CLTS VARCHAR (40) NULL,
    PROC_TRAT_TRANS_RESI INT NULL,
    DETALH_PROCESSO VARCHAR (40) NULL,
    QUAN_MEN_COND INT NULL,
    QUAN_MEN_CLTD INT NULL,
    DEST_FINAL_COD__1 VARCHAR (40) NULL,
    DEST_FINAL_COD__2 VARCHAR (40) NULL,
    DEST_FINAL_COD__3 VARCHAR (40) NULL,
    DEST_FINAL_COD__4 VARCHAR (40) NULL,
    DEST_FINAL_COD__5 VARCHAR (40) NULL,
    DEST_FINAL_COD__6 VARCHAR (40) NULL,
    DEST_FINAL_COD__7 VARCHAR (40) NULL,
    DEST_FINAL_COD__8 VARCHAR (40) NULL,
    DEST_FINAL_COD__9 VARCHAR (40) NULL,
    DEST_FINAL_COD__10 VARCHAR (40) NULL,
    DEST_FINAL_COD__11 VARCHAR (40) NULL,
    DEST_FINAL_COD__12 VARCHAR (40) NULL,
    DEST_FINAL_COD__13 VARCHAR (40) NULL,
    DEST_FINAL_COD__14 VARCHAR (40) NULL,
    DEST_FINAL_COD__15 VARCHAR (40) NULL,
    DEST_FINAL_COD__16 VARCHAR (40) NULL,
    LOC_DESTI_FINAL__Latitude DOUBLE PRECISION NULL,
    LOC_DESTI_FINAL__Longitude DOUBLE PRECISION NULL,
    LOC_DESTI_FINAL__Accuracy DOUBLE PRECISION NULL,
    LOC_DESTI_FINAL__Altitude DOUBLE PRECISION NULL,
    LOC_DESTI_FINAL__Timestamp TIMESTAMP NULL,
    DIAS_SEMANA_FEIRA__1 VARCHAR (40) NULL,
    DIAS_SEMANA_FEIRA__2 VARCHAR (40) NULL,
    DIAS_SEMANA_FEIRA__3 VARCHAR (40) NULL,
    DIAS_SEMANA_FEIRA__4 VARCHAR (40) NULL,
    DIAS_SEMANA_FEIRA__5 VARCHAR (40) NULL,
    DIAS_SEMANA_FEIRA__6 VARCHAR (40) NULL,
    DIAS_SEMANA_FEIRA__7 VARCHAR (40) NULL,
    COMO_ARMAZE_RESI__1 VARCHAR (40) NULL,
    COMO_ARMAZE_RESI__2 VARCHAR (40) NULL,
    COMO_ARMAZE_RESI__3 VARCHAR (40) NULL,
    COMO_ARMAZE_RESI__4 VARCHAR (40) NULL,
    QTDE_FOTO_RESI INT NULL,
    RESP_INFO_LIMP_URB__0 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__1 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__2 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__3 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__4 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__5 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__6 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__7 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__8 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__9 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__10 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__11 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__12 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__13 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__14 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__15 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__16 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__17 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__18 VARCHAR (40) NULL,
    RESP_INFO_LIMP_URB__19 VARCHAR (40) NULL,
    OBS_LIMP_URB VARCHAR (40) NULL
);





CREATE TABLE RESIDUOS_SOLIDOS_R_QUANT_COL_MES_RSS(
    interview__key VARCHAR(11) NOT NULL,
    interview__id VARCHAR(32) NOT NULL,
    R_LOCALIDADE__id SMALL SMALLINT NOT NULL,
    R_QUANT_COL_MES_RCC__id SMALLINT NOT NULL,
    QUANT_COL_MM_RC DECIMAL NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_R_QUANT_ECON_ATEND(
    interview__key VARCHAR(11) NOT NULL,
    interview__id VARCHAR(32) NOT NULL,
    R_QUANT_ECON_ATEND__id SMALLINT NOT NULL,
    QUANT_ECON_ATEND_17 DECIMAL NULL,
    QUANT_ECON_ATEND_18 DECIMAL NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_R_RESP_INFORM(
    interview__key VARCHAR(11) NOT NULL,
    interview__id VARCHAR(32) NOT NULL,
    R_LOCALIDADE__id SMALLINT NOT NULL,
    TRATAM_DISP_FINAL__id SMALLINT NOT NULL,
    R_RESP_INFORM__id SMALLINT NOT NULL,
    RESP_INFORMACOES VARCHAR(150) NULL,
    CARGOS_FUNC VARCHAR(150) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_R_SIST_COB_17_18(
    interview__key VARCHAR(11) NOT NULL,
    interview__id VARCHAR(32) NOT NULL,
    R_SIST_COB_17_18__id SMALLINT NOT NULL,
    SIST_COB SMALLINT NULL,
    OUTRO_SIST_COB_17_18 VARCHAR(150) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_R_UNI_GERADORA(
    interview__key VARCHAR(11) NOT NULL,
    interview__id VARCHAR(32) NOT NULL,
    R_LOCALIDADE__id SMALLINT NOT NULL,
    R_UNI_GERADORA__id SMALLINT NOT NULL,
    UNI_GERADORA__0 VARCHAR(150) NULL,
    UNI_GERADORA__1 VARCHAR(150) NULL,
    UNI_GERADORA__2 VARCHAR(150) NULL,
    UNI_GERADORA__3 VARCHAR(150) NULL,
    UNI_GERADORA__4 VARCHAR(150) NULL,
    UNI_GERADORA__5 VARCHAR(150) NULL,
    UNI_GERADORA__6 VARCHAR(150) NULL,
    OUTRA_UNI_GERA VARCHAR(150) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_R_VAL_PREV_REAL(
    interview__key VARCHAR(11) NOT NULL,
    interview__id VARCHAR(32) NOT NULL,
    R_VAL_PREV_REAL__id SMALLINT NOT NULL,
    VAL_PREV_18 DECIMAL NULL,
    VAL_REAL_18 DECIMAL NULL,
    VAL_PREV_17 DECIMAL NULL,
    VAL_REAL_17 DECIMAL NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_ROST_RESP_AELSLU(
    interview__key VARCHAR(11) NOT NULL,
    interview__id VARCHAR(32) NOT NULL,
    ROST_RESP_AELSLU__id SMALLINT NOT NULL,
    RESP_INF VARCHAR(150) NULL,
    CARGO_FUNC VARCHAR(150) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_ROST_RESP_AL(
    interview__key VARCHAR(11) NOT NULL,
    interview__id VARCHAR(32) NOT NULL,
    ROST_RESP_AL__id SMALLINT NOT NULL,
    RESP_INF_AAITSLU VARCHAR(150),
    CARG_FUNC_AL VARCHAR(150) NULL,
    CARG_FUNC_AAITSLU VARCHAR(150) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_ROST_RESP_CARG_FUNC(
    interview__key VARCHAR(11) NOT NULL,
    interview__id VARCHAR(32) NOT NULL,
    R_LOCALIDADE__id SMALLINT NOT NULL,
    ROST_RES_GER_LOC__id SMALLINT NOT NULL,
    ROST_RESP_CARG_FUNC__id SMALLINT NOT NULL,
    RESP_PELAS_INFO_RESI VARCHAR(150) NULL,
    CARGO_FUNCAO_RESI VARCHAR(150) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_ROST_RESP_INFO_CARG(
    interview__key VARCHAR(11) NOT NULL,
    interview__id VARCHAR(32) NOT NULL,
    R_LOCALIDADE__id SMALLINT NOT NULL,
    ROST_RESP_INFO_CARG__id SMALLINT NOT NULL,
    RESP_INF_RSI VARCHAR(150) NULL,
    CARGO_FUNC_RSI VARCHAR(150) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_ROST_RESP_LIMP_URB(
    interview__key VARCHAR(11) NOT NULL,
    interview__id VARCHAR(32) NOT NULL,
    R_LOCALIDADE__id SMALLINT NOT NULL,
    ROST_SERVI_LIMP_PUB__id SMALLINT NOT NULL,
    ROST_RESP_LIMP_URB__id SMALLINT NOT NULL,
    RESP_INFO_LIMP_URB VARCHAR(150) NULL,
    CARG_FUNC_LIMP_URB VARCHAR(150) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_ROST_RESP_RCC(
    interview__key VARCHAR(11) NOT NULL,
    interview__id VARCHAR(32) NOT NULL,
    R_LOCALIDADE__id SMALLINT NOT NULL,
    ROST_RESP_RCC__id SMALLINT NOT NULL,
    RESP_INF_RCC VARCHAR(150) NULL,
    CARGO_FUNC_RCC VARCHAR(150) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_ROST_RESP_RSC(
    interview__key VARCHAR(11) NOT NULL,
    interview__id VARCHAR(32) NOT NULL,
    R_LOCALIDADE__id SMALLINT NOT NULL,
    ROST_RESP_RSC__id SMALLINT NOT NULL,
    RESP_INF_RSC VARCHAR(150) NULL,
    CARGO_FUNC_RSC VARCHAR(150) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_ROST_RESP_RSS(
    interview__key VARCHAR(11) NOT NULL,
    interview__id VARCHAR(32) NOT NULL,
    R_LOCALIDADE__id SMALLINT NOT NULL,
    R_UNI_GERADORA__id SMALLINT NOT NULL,
    INFOUNIDGERADORA__id SMALLINT NOT NULL,
    ROST_RESP_RSS__id SMALLINT NOT NULL,
    RESP_INF_RSS VARCHAR(150) NULL,
    CARGO_FUNC_RSS VARCHAR(150) NULL
);



CREATE TABLE RESIDUOS_SOLIDOS_R_COM_LOC_RSC (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT NULL,
    R_COM_LOC_RSC__id INT NULL,
    IDENT_COM_LOC_RSC VARCHAR (40) NULL,
    END_COM_LOC_RSC VARCHAR (40) NULL,
    COORD_COM_LOC_RSC__Latitude DOUBLE PRECISION NULL,
    COORD_COM_LOC_RSC__Longitude DOUBLE PRECISION NULL,
    COORD_COM_LOC_RSC__Accuracy DOUBLE PRECISION NULL,
    COORD_COM_LOC_RSC__Altitude DOUBLE PRECISION NULL,
    COORD_COM_LOC_RSC__Timestamp TIMESTAMP
);


CREATE TABLE RESIDUOS_SOLIDOS_R_ESC_FUN_LIM_PUB (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_ESC_FUN_LIM_PUB__id INT,
    QUANT_FUN_TERC INT NULL,
    QUANT_FUN_PROP INT NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_R_IMG_RCC (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    R_IMG_RCC__id INT,
    IMG_RCC VARCHAR (120) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_R_IMG_RSC (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    R_IMG_RSC__id INT,
    IMG_RSC VARCHAR (120) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_R_IMG_RSI (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    R_IMG_RSI__id INT,
    IMG_RSI VARCHAR (120) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_R_IMG_RSS (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    R_UNI_GERADORA__id INT,
    INFOUNIDGERADORA__id INT,
    R_IMG_RSS__id INT,
    IMG_RSS VARCHAR (120) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_R_IND_LOC_RSI (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    R_IND_LOC_RSI__id INT,
    INDENT_IND_LOC_RSI INT,
    END_IND_LOC_RSI VARCHAR (40),
    COORD_IND_LOC_RSI VARCHAR (40)
);


CREATE TABLE RESIDUOS_SOLIDOS_R_PRIN_RES_GER_RSI (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    R_PRIN_RES_GER_RSI__id INT,
    IDENT_PRINC_RES_GER_RSI VARCHAR (40)
);



CREATE TABLE RESIDUOS_SOLIDOS_ROST_CUST_MED_ANUAL (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    ROST_CUST_MED_ANUAL__id INT,
    ANOCAMPANHASMUNI INT NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_ROST_FT_LIMP_URB (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    ROST_CUST_MED_ANUAL__id INT,
    ANOCAMPANHASMUNI INT NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_ROST_GR_ESCOL_FUN (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    ROST_GR_ESCOL_FUN__id INT,
    FUNCAODOFUNCIONARIO INT NULL,
    OUTRAFUNCAO VARCHAR (40) NULL,
    GRAUESCOLARIDADE__0 VARCHAR (40) NULL,
    GRAUESCOLARIDADE__1 VARCHAR (40) NULL,
    GRAUESCOLARIDADE__2 VARCHAR (40) NULL,
    GRAUESCOLARIDADE__3 VARCHAR (40) NULL,
    SITUACAOCONTRATUA INT NULL
);


CREATE TABLE RESIDUOS_SOLIDOS_R_CAP_TREI_FUN_LIMP_URB (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_CAP_TREI_FUN_LIMP_URB__id INT,
    QUANT_FUNC INT NULL,
    HORAS_CAP_TREI INT NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_ROST_INFO_LOC (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    FREQ_COLETA_RSD__id INT,
    ROST_INFO_LOC__id INT,
    LOCAL_BAIRRO_RSD VARCHAR (40) NULL,
    FREQ_COLETA_RSD_1 INT NULL,
    TURNO_COLETA_RSD INT NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_ROST_RESP_RST (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    ROST_RESP_RST__id INT,
    RESP_INF_RST VARCHAR (40) NULL,
    CARGO_FUNC_RST  VARCHAR (40) NULL
);



CREATE TABLE RESIDUOS_SOLIDOS_ROST_OBSERV_FT (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    ROST_RES_GER_LOC__id INT,
    ROST_OBSERV_FT__id INT,
    INSER_FOTO_OBS VARCHAR (120)
);

CREATE TABLE RESIDUOS_SOLIDOS_ROST_OBS_CLT_SLTV (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    ROST_OBS_CLT_SLTV__id INT,
    FTO_CLT_SLTV VARCHAR (120)
);

CREATE TABLE RESIDUOS_SOLIDOS_ROST_QTDE_FOTO_RST (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    ROST_QTDE_FOTO_RST__id INT,
    FOTOS_FORMULARIO_RSS VARCHAR (120)
);

CREATE TABLE RESIDUOS_SOLIDOS_ROST_RES_GER_LOC (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    ROST_RES_GER_LOC__id INT,
    SIST_LOGIS_REVER_RESI INT NULL,
    CENT_RCPC_TRIA_RESI INT NULL,
    LOC_CNT_RCP_TRIA__Latitude DOUBLE PRECISION NULL,
    LOC_CNT_RCP_TRIA__Longitude DOUBLE PRECISION NULL,
    LOC_CNT_RCP_TRIA__Accuracy DOUBLE PRECISION NULL,
    LOC_CNT_RCP_TRIA__Altitude DOUBLE PRECISION NULL,
    LOC_CNT_RCP_TRIA__Timestamp TIMESTAMP NULL,
    QUL_PRT_CMM_LOC__1 VARCHAR (40) NULL,
    QUL_PRT_CMM_LOC__2 VARCHAR (40) NULL,
    QUL_PRT_CMM_LOC__3 VARCHAR (40) NULL,
    QUL_PRT_CMM_LOC__4 VARCHAR (40) NULL,
    DESC_QUAIS_OUT_PRAT VARCHAR (40) NULL,
    CM_SERV_CLT_RESI INT NULL,
    DCVR_OUT_SRV_CLT_SLTV VARCHAR (40) NULL,
    QNT_GRD_INFO INT NULL,
    QUAL_UNIDD_MEDIDA VARCHAR (40) NULL,
    INS_QNTD_GRD VARCHAR (40) NULL,
    EXIG_TRIP_LVG_EMBLGS INT NULL,
    QUANT_FOTOS_OBSERV INT NULL,
    RESP_PELAS_INFO_RESI__0 VARCHAR (40) NULL,
    RESP_PELAS_INFO_RESI__1 VARCHAR (40) NULL,
    RESP_PELAS_INFO_RESI__2 VARCHAR (40) NULL,
    RESP_PELAS_INFO_RESI__3 VARCHAR (40) NULL,
    RESP_PELAS_INFO_RESI__4 VARCHAR (40) NULL,
    RESP_PELAS_INFO_RESI__5 VARCHAR (40) NULL,
    RESP_PELAS_INFO_RESI__6 VARCHAR (40) NULL,
    RESP_PELAS_INFO_RESI__7 VARCHAR (40) NULL,
    RESP_PELAS_INFO_RESI__8 VARCHAR (40) NULL,
    RESP_PELAS_INFO_RESI__9 VARCHAR (40) NULL,
    RESP_PELAS_INFO_RESI__10 VARCHAR (40) NULL,
    RESP_PELAS_INFO_RESI__11 VARCHAR (40) NULL,
    RESP_PELAS_INFO_RESI__12 VARCHAR (40) NULL,
    RESP_PELAS_INFO_RESI__13 VARCHAR (40) NULL,
    RESP_PELAS_INFO_RESI__14 VARCHAR (40) NULL,
    OBS_RESIDUOS VARCHAR (40) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_ROSTER_INF_COLET_SELET (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    ROSTER_INF_COLET_SELET__id INT,
    INFR_VEICULO__1 VARCHAR (40) NULL,
    INFR_VEICULO__2 VARCHAR (40) NULL,
    INFR_VEICULO__3 VARCHAR (40) NULL,
    INFR_VEICULO__4 VARCHAR (40) NULL,
    INFR_VEICULO__5 VARCHAR (40) NULL,
    INFR_VEICULO__6 VARCHAR (40) NULL,
    INFR_VEICULO__7 VARCHAR (40) NULL,
    INFR_VEICULO__8 VARCHAR (40) NULL,
    INFR_VEICULO__9 VARCHAR (40) NULL,
    INFR_VEICULO__10 VARCHAR (40) NULL,
    INFR_VEICULO__11 VARCHAR (40) NULL,
    INFR_VEICULO__12 VARCHAR (40) NULL,
    INFR_VEICULO__13 VARCHAR (40) NULL,
    INFR_VEICULO__14 VARCHAR (40) NULL,
    QUANT_VEICULO INT NULL,
    COND_CONSER_VEICU  VARCHAR (40) NULL,
    FOTOS_VEICULOS VARCHAR (120) NULL,
    QUANT_GALPOES INT NULL,
    AREA_GALPOES DECIMAL NULL,
    LOC_GALPOES__Latitude DOUBLE PRECISION NULL,
    LOC_GALPOES__Longitude DOUBLE PRECISION NULL,
    LOC_GALPOES__Accuracy DOUBLE PRECISION NULL,
    LOC_GALPOES__Altitude DOUBLE PRECISION NULL,
    LOC_GALPOES__Timestamp TIMESTAMP NULL,
    COND_GALPOES VARCHAR (40) NULL,
    FOT_GALPOES VARCHAR (120) NULL,
    QUANT_PRENSA INT NULL,
    CAPA_PRENSA DECIMAL NULL,
    COND_PRENSA  VARCHAR (40) NULL,
    FOTOS_PRENSA VARCHAR (120) NULL
);

CREATE TABLE RESIDUOS_SOLIDOS_ROSTER_TRIA_MAT (
    interview__key VARCHAR (11),
    interview__id VARCHAR (32),
    R_LOCALIDADE__id INT,
    ROSTER_TRIA_MAT__id INT,
    ITEM_COMERCIALIZADO  VARCHAR (40) NULL,
    QTD_ITEM_COMERC INT NULL,
    LOC_ITEM_COMERCI__1  VARCHAR (40) NULL,
    LOC_ITEM_COMERCI__2 VARCHAR (40) NULL,
    LOC_ITEM_COMERCI__3 VARCHAR (40) NULL,
    DESCR_LOC_ITEM_COMERCI VARCHAR (40) NULL
);



