COPY DRENAGEM
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\DRENAGEM.tab' CSV HEADER DELIMITER E'\t';

COPY DRENAGEM_ROSTER_LOC_SEDE
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\ROSTER_LOC_SEDE.tab' CSV HEADER DELIMITER E'\t';

COPY DRENAGEM_ROSTER_LOC_DRE1
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\ROSTER_LOC_DRE1.tab' CSV HEADER DELIMITER E'\t';

COPY DRENAGEM_ROSTER_PRIN_MED
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\ROSTER_PRIN_MED.tab' CSV HEADER DELIMITER E'\t';

COPY DRENAGEM_ROSTER_SUB_BACIA
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\ROSTER_SUB_BACIA.tab' CSV HEADER DELIMITER E'\t';

COPY DRENAGEM_ROSTER_DIA_UTILI
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\ROSTER_DIA_UTILI.tab' CSV HEADER DELIMITER E'\t';

COPY DRENAGEM_ROSTER_LOC_DREN2
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\ROSTER_LOC_DREN2.tab' CSV HEADER DELIMITER E'\t';

COPY DRENAGEM_ROSTER_MICR_DREN
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\ROSTER_MICR_DREN.tab' CSV HEADER DELIMITER E'\t';

COPY DRENAGEM_ROSTER_MAT_COMP3
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\ROSTER_MAT_COMP3.tab' CSV HEADER DELIMITER E'\t';

COPY DRENAGEM_R_FOTOS_SIS_DREN1
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\R_FOTOS_SIS_DREN1.tab' CSV HEADER DELIMITER E'\t';

COPY DRENAGEM_ROSTER_LOC_DREN3
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\ROSTER_LOC_DREN3.tab' CSV HEADER DELIMITER E'\t';

COPY DRENAGEM_ROSTER_MACR_DREN2
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\ROSTER_MACR_DREN2.tab' CSV HEADER DELIMITER E'\t';

COPY DRENAGEM_ROSTER_PROB_DREN2
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\ROSTER_PROB_DREN2.tab' CSV HEADER DELIMITER E'\t';

COPY DRENAGEM_ROSTER_PROB_DREN
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\ROSTER_PROB_DREN.tab' CSV HEADER DELIMITER E'\t';

COPY DRENAGEM _ROSTER_TIP_SIST1
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\ROSTER_TIP_SIST1.tab' CSV HEADER DELIMITER E'\t';

COPY DRENAGEM_R_FOTOS_SIS_DREN
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\R_FOTOS_SIS_DREN.tab' CSV HEADER DELIMITER E'\t';

COPY DRENAGEM_R_PROB_DREN_1
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\R_PROB_DREN_1.tab' CSV HEADER DELIMITER E'\t';

COPY DRENAGEM_ROSTER_TIP_SIST2
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\ROSTER_TIP_SIST2.tab' CSV HEADER DELIMITER E'\t';

COPY DRENAGEM_R_FOTOS_SIS_DREN2
	FROM 'C:\Users\Public\DRENAGEM_4_Tabular_All\R_FOTOS_SIS_DREN2.tab' CSV HEADER DELIMITER E'\t';
